// Code generated by ent, DO NOT EDIT.

package channelinvitecode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the channelinvitecode type in the database.
	Label = "channel_invite_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBatchID holds the string denoting the batch_id field in the database.
	FieldBatchID = "batch_id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMaxUses holds the string denoting the max_uses field in the database.
	FieldMaxUses = "max_uses"
	// FieldUsedCount holds the string denoting the used_count field in the database.
	FieldUsedCount = "used_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeBatch holds the string denoting the batch edge name in mutations.
	EdgeBatch = "batch"
	// EdgeUsages holds the string denoting the usages edge name in mutations.
	EdgeUsages = "usages"
	// Table holds the table name of the channelinvitecode in the database.
	Table = "channel_invite_codes"
	// BatchTable is the table that holds the batch relation/edge.
	BatchTable = "channel_invite_codes"
	// BatchInverseTable is the table name for the ChannelInviteBatch entity.
	// It exists in this package in order to avoid circular dependency with the "channelinvitebatch" package.
	BatchInverseTable = "channel_invite_batches"
	// BatchColumn is the table column denoting the batch relation/edge.
	BatchColumn = "batch_id"
	// UsagesTable is the table that holds the usages relation/edge.
	UsagesTable = "channel_invite_code_usages"
	// UsagesInverseTable is the table name for the ChannelInviteCodeUsage entity.
	// It exists in this package in order to avoid circular dependency with the "channelinvitecodeusage" package.
	UsagesInverseTable = "channel_invite_code_usages"
	// UsagesColumn is the table column denoting the usages relation/edge.
	UsagesColumn = "code_id"
)

// Columns holds all SQL columns for channelinvitecode fields.
var Columns = []string{
	FieldID,
	FieldBatchID,
	FieldCode,
	FieldStatus,
	FieldMaxUses,
	FieldUsedCount,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultMaxUses holds the default value on creation for the "max_uses" field.
	DefaultMaxUses int
	// DefaultUsedCount holds the default value on creation for the "used_count" field.
	DefaultUsedCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ChannelInviteCode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBatchID orders the results by the batch_id field.
func ByBatchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMaxUses orders the results by the max_uses field.
func ByMaxUses(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxUses, opts...).ToFunc()
}

// ByUsedCount orders the results by the used_count field.
func ByUsedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByBatchField orders the results by batch field.
func ByBatchField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBatchStep(), sql.OrderByField(field, opts...))
	}
}

// ByUsagesCount orders the results by usages count.
func ByUsagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsagesStep(), opts...)
	}
}

// ByUsages orders the results by usages terms.
func ByUsages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newBatchStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BatchInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BatchTable, BatchColumn),
	)
}
func newUsagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsagesTable, UsagesColumn),
	)
}
