// Code generated by ent, DO NOT EDIT.

package channelinvitecode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLTE(FieldID, id))
}

// BatchID applies equality check predicate on the "batch_id" field. It's identical to BatchIDEQ.
func BatchID(v int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldBatchID, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldCode, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldStatus, v))
}

// MaxUses applies equality check predicate on the "max_uses" field. It's identical to MaxUsesEQ.
func MaxUses(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldMaxUses, v))
}

// UsedCount applies equality check predicate on the "used_count" field. It's identical to UsedCountEQ.
func UsedCount(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldUsedCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// BatchIDEQ applies the EQ predicate on the "batch_id" field.
func BatchIDEQ(v int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldBatchID, v))
}

// BatchIDNEQ applies the NEQ predicate on the "batch_id" field.
func BatchIDNEQ(v int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNEQ(FieldBatchID, v))
}

// BatchIDIn applies the In predicate on the "batch_id" field.
func BatchIDIn(vs ...int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldIn(FieldBatchID, vs...))
}

// BatchIDNotIn applies the NotIn predicate on the "batch_id" field.
func BatchIDNotIn(vs ...int64) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNotIn(FieldBatchID, vs...))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldContainsFold(FieldCode, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldContainsFold(FieldStatus, v))
}

// MaxUsesEQ applies the EQ predicate on the "max_uses" field.
func MaxUsesEQ(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldMaxUses, v))
}

// MaxUsesNEQ applies the NEQ predicate on the "max_uses" field.
func MaxUsesNEQ(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNEQ(FieldMaxUses, v))
}

// MaxUsesIn applies the In predicate on the "max_uses" field.
func MaxUsesIn(vs ...int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldIn(FieldMaxUses, vs...))
}

// MaxUsesNotIn applies the NotIn predicate on the "max_uses" field.
func MaxUsesNotIn(vs ...int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNotIn(FieldMaxUses, vs...))
}

// MaxUsesGT applies the GT predicate on the "max_uses" field.
func MaxUsesGT(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGT(FieldMaxUses, v))
}

// MaxUsesGTE applies the GTE predicate on the "max_uses" field.
func MaxUsesGTE(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGTE(FieldMaxUses, v))
}

// MaxUsesLT applies the LT predicate on the "max_uses" field.
func MaxUsesLT(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLT(FieldMaxUses, v))
}

// MaxUsesLTE applies the LTE predicate on the "max_uses" field.
func MaxUsesLTE(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLTE(FieldMaxUses, v))
}

// UsedCountEQ applies the EQ predicate on the "used_count" field.
func UsedCountEQ(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldUsedCount, v))
}

// UsedCountNEQ applies the NEQ predicate on the "used_count" field.
func UsedCountNEQ(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNEQ(FieldUsedCount, v))
}

// UsedCountIn applies the In predicate on the "used_count" field.
func UsedCountIn(vs ...int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldIn(FieldUsedCount, vs...))
}

// UsedCountNotIn applies the NotIn predicate on the "used_count" field.
func UsedCountNotIn(vs ...int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNotIn(FieldUsedCount, vs...))
}

// UsedCountGT applies the GT predicate on the "used_count" field.
func UsedCountGT(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGT(FieldUsedCount, v))
}

// UsedCountGTE applies the GTE predicate on the "used_count" field.
func UsedCountGTE(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGTE(FieldUsedCount, v))
}

// UsedCountLT applies the LT predicate on the "used_count" field.
func UsedCountLT(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLT(FieldUsedCount, v))
}

// UsedCountLTE applies the LTE predicate on the "used_count" field.
func UsedCountLTE(v int) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLTE(FieldUsedCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasBatch applies the HasEdge predicate on the "batch" edge.
func HasBatch() predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BatchTable, BatchColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBatchWith applies the HasEdge predicate on the "batch" edge with a given conditions (other predicates).
func HasBatchWith(preds ...predicate.ChannelInviteBatch) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(func(s *sql.Selector) {
		step := newBatchStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsages applies the HasEdge predicate on the "usages" edge.
func HasUsages() predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsagesTable, UsagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsagesWith applies the HasEdge predicate on the "usages" edge with a given conditions (other predicates).
func HasUsagesWith(preds ...predicate.ChannelInviteCodeUsage) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(func(s *sql.Selector) {
		step := newUsagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChannelInviteCode) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChannelInviteCode) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChannelInviteCode) predicate.ChannelInviteCode {
	return predicate.ChannelInviteCode(sql.NotPredicates(p))
}
