// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecode"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecodeusage"
)

// ChannelInviteCodeCreate is the builder for creating a ChannelInviteCode entity.
type ChannelInviteCodeCreate struct {
	config
	mutation *ChannelInviteCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBatchID sets the "batch_id" field.
func (_c *ChannelInviteCodeCreate) SetBatchID(v int64) *ChannelInviteCodeCreate {
	_c.mutation.SetBatchID(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *ChannelInviteCodeCreate) SetCode(v string) *ChannelInviteCodeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChannelInviteCodeCreate) SetStatus(v string) *ChannelInviteCodeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ChannelInviteCodeCreate) SetNillableStatus(v *string) *ChannelInviteCodeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMaxUses sets the "max_uses" field.
func (_c *ChannelInviteCodeCreate) SetMaxUses(v int) *ChannelInviteCodeCreate {
	_c.mutation.SetMaxUses(v)
	return _c
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_c *ChannelInviteCodeCreate) SetNillableMaxUses(v *int) *ChannelInviteCodeCreate {
	if v != nil {
		_c.SetMaxUses(*v)
	}
	return _c
}

// SetUsedCount sets the "used_count" field.
func (_c *ChannelInviteCodeCreate) SetUsedCount(v int) *ChannelInviteCodeCreate {
	_c.mutation.SetUsedCount(v)
	return _c
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_c *ChannelInviteCodeCreate) SetNillableUsedCount(v *int) *ChannelInviteCodeCreate {
	if v != nil {
		_c.SetUsedCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelInviteCodeCreate) SetCreatedAt(v time.Time) *ChannelInviteCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelInviteCodeCreate) SetNillableCreatedAt(v *time.Time) *ChannelInviteCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChannelInviteCodeCreate) SetUpdatedAt(v time.Time) *ChannelInviteCodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChannelInviteCodeCreate) SetNillableUpdatedAt(v *time.Time) *ChannelInviteCodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetBatch sets the "batch" edge to the ChannelInviteBatch entity.
func (_c *ChannelInviteCodeCreate) SetBatch(v *ChannelInviteBatch) *ChannelInviteCodeCreate {
	return _c.SetBatchID(v.ID)
}

// AddUsageIDs adds the "usages" edge to the ChannelInviteCodeUsage entity by IDs.
func (_c *ChannelInviteCodeCreate) AddUsageIDs(ids ...int64) *ChannelInviteCodeCreate {
	_c.mutation.AddUsageIDs(ids...)
	return _c
}

// AddUsages adds the "usages" edges to the ChannelInviteCodeUsage entity.
func (_c *ChannelInviteCodeCreate) AddUsages(v ...*ChannelInviteCodeUsage) *ChannelInviteCodeCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageIDs(ids...)
}

// Mutation returns the ChannelInviteCodeMutation object of the builder.
func (_c *ChannelInviteCodeCreate) Mutation() *ChannelInviteCodeMutation {
	return _c.mutation
}

// Save creates the ChannelInviteCode in the database.
func (_c *ChannelInviteCodeCreate) Save(ctx context.Context) (*ChannelInviteCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelInviteCodeCreate) SaveX(ctx context.Context) *ChannelInviteCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelInviteCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelInviteCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelInviteCodeCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := channelinvitecode.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.MaxUses(); !ok {
		v := channelinvitecode.DefaultMaxUses
		_c.mutation.SetMaxUses(v)
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		v := channelinvitecode.DefaultUsedCount
		_c.mutation.SetUsedCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := channelinvitecode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := channelinvitecode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelInviteCodeCreate) check() error {
	if _, ok := _c.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch_id", err: errors.New(`ent: missing required field "ChannelInviteCode.batch_id"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "ChannelInviteCode.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := channelinvitecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ChannelInviteCode.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ChannelInviteCode.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := channelinvitecode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChannelInviteCode.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxUses(); !ok {
		return &ValidationError{Name: "max_uses", err: errors.New(`ent: missing required field "ChannelInviteCode.max_uses"`)}
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		return &ValidationError{Name: "used_count", err: errors.New(`ent: missing required field "ChannelInviteCode.used_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChannelInviteCode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChannelInviteCode.updated_at"`)}
	}
	if len(_c.mutation.BatchIDs()) == 0 {
		return &ValidationError{Name: "batch", err: errors.New(`ent: missing required edge "ChannelInviteCode.batch"`)}
	}
	return nil
}

func (_c *ChannelInviteCodeCreate) sqlSave(ctx context.Context) (*ChannelInviteCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelInviteCodeCreate) createSpec() (*ChannelInviteCode, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelInviteCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelinvitecode.Table, sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(channelinvitecode.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(channelinvitecode.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.MaxUses(); ok {
		_spec.SetField(channelinvitecode.FieldMaxUses, field.TypeInt, value)
		_node.MaxUses = value
	}
	if value, ok := _c.mutation.UsedCount(); ok {
		_spec.SetField(channelinvitecode.FieldUsedCount, field.TypeInt, value)
		_node.UsedCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelinvitecode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(channelinvitecode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecode.BatchTable,
			Columns: []string{channelinvitecode.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BatchID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitecode.UsagesTable,
			Columns: []string{channelinvitecode.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelInviteCode.Create().
//		SetBatchID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelInviteCodeUpsert) {
//			SetBatchID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelInviteCodeCreate) OnConflict(opts ...sql.ConflictOption) *ChannelInviteCodeUpsertOne {
	_c.conflict = opts
	return &ChannelInviteCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelInviteCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelInviteCodeCreate) OnConflictColumns(columns ...string) *ChannelInviteCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelInviteCodeUpsertOne{
		create: _c,
	}
}

type (
	// ChannelInviteCodeUpsertOne is the builder for "upsert"-ing
	//  one ChannelInviteCode node.
	ChannelInviteCodeUpsertOne struct {
		create *ChannelInviteCodeCreate
	}

	// ChannelInviteCodeUpsert is the "OnConflict" setter.
	ChannelInviteCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetBatchID sets the "batch_id" field.
func (u *ChannelInviteCodeUpsert) SetBatchID(v int64) *ChannelInviteCodeUpsert {
	u.Set(channelinvitecode.FieldBatchID, v)
	return u
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsert) UpdateBatchID() *ChannelInviteCodeUpsert {
	u.SetExcluded(channelinvitecode.FieldBatchID)
	return u
}

// SetCode sets the "code" field.
func (u *ChannelInviteCodeUpsert) SetCode(v string) *ChannelInviteCodeUpsert {
	u.Set(channelinvitecode.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsert) UpdateCode() *ChannelInviteCodeUpsert {
	u.SetExcluded(channelinvitecode.FieldCode)
	return u
}

// SetStatus sets the "status" field.
func (u *ChannelInviteCodeUpsert) SetStatus(v string) *ChannelInviteCodeUpsert {
	u.Set(channelinvitecode.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsert) UpdateStatus() *ChannelInviteCodeUpsert {
	u.SetExcluded(channelinvitecode.FieldStatus)
	return u
}

// SetMaxUses sets the "max_uses" field.
func (u *ChannelInviteCodeUpsert) SetMaxUses(v int) *ChannelInviteCodeUpsert {
	u.Set(channelinvitecode.FieldMaxUses, v)
	return u
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsert) UpdateMaxUses() *ChannelInviteCodeUpsert {
	u.SetExcluded(channelinvitecode.FieldMaxUses)
	return u
}

// AddMaxUses adds v to the "max_uses" field.
func (u *ChannelInviteCodeUpsert) AddMaxUses(v int) *ChannelInviteCodeUpsert {
	u.Add(channelinvitecode.FieldMaxUses, v)
	return u
}

// SetUsedCount sets the "used_count" field.
func (u *ChannelInviteCodeUpsert) SetUsedCount(v int) *ChannelInviteCodeUpsert {
	u.Set(channelinvitecode.FieldUsedCount, v)
	return u
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsert) UpdateUsedCount() *ChannelInviteCodeUpsert {
	u.SetExcluded(channelinvitecode.FieldUsedCount)
	return u
}

// AddUsedCount adds v to the "used_count" field.
func (u *ChannelInviteCodeUpsert) AddUsedCount(v int) *ChannelInviteCodeUpsert {
	u.Add(channelinvitecode.FieldUsedCount, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelInviteCodeUpsert) SetUpdatedAt(v time.Time) *ChannelInviteCodeUpsert {
	u.Set(channelinvitecode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsert) UpdateUpdatedAt() *ChannelInviteCodeUpsert {
	u.SetExcluded(channelinvitecode.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChannelInviteCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelInviteCodeUpsertOne) UpdateNewValues() *ChannelInviteCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(channelinvitecode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelInviteCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelInviteCodeUpsertOne) Ignore() *ChannelInviteCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelInviteCodeUpsertOne) DoNothing() *ChannelInviteCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelInviteCodeCreate.OnConflict
// documentation for more info.
func (u *ChannelInviteCodeUpsertOne) Update(set func(*ChannelInviteCodeUpsert)) *ChannelInviteCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelInviteCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *ChannelInviteCodeUpsertOne) SetBatchID(v int64) *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsertOne) UpdateBatchID() *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.UpdateBatchID()
	})
}

// SetCode sets the "code" field.
func (u *ChannelInviteCodeUpsertOne) SetCode(v string) *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsertOne) UpdateCode() *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.UpdateCode()
	})
}

// SetStatus sets the "status" field.
func (u *ChannelInviteCodeUpsertOne) SetStatus(v string) *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsertOne) UpdateStatus() *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.UpdateStatus()
	})
}

// SetMaxUses sets the "max_uses" field.
func (u *ChannelInviteCodeUpsertOne) SetMaxUses(v int) *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.SetMaxUses(v)
	})
}

// AddMaxUses adds v to the "max_uses" field.
func (u *ChannelInviteCodeUpsertOne) AddMaxUses(v int) *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.AddMaxUses(v)
	})
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsertOne) UpdateMaxUses() *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.UpdateMaxUses()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *ChannelInviteCodeUpsertOne) SetUsedCount(v int) *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *ChannelInviteCodeUpsertOne) AddUsedCount(v int) *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsertOne) UpdateUsedCount() *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.UpdateUsedCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelInviteCodeUpsertOne) SetUpdatedAt(v time.Time) *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsertOne) UpdateUpdatedAt() *ChannelInviteCodeUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChannelInviteCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelInviteCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelInviteCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelInviteCodeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelInviteCodeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelInviteCodeCreateBulk is the builder for creating many ChannelInviteCode entities in bulk.
type ChannelInviteCodeCreateBulk struct {
	config
	err      error
	builders []*ChannelInviteCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the ChannelInviteCode entities in the database.
func (_c *ChannelInviteCodeCreateBulk) Save(ctx context.Context) ([]*ChannelInviteCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelInviteCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelInviteCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelInviteCodeCreateBulk) SaveX(ctx context.Context) []*ChannelInviteCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelInviteCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelInviteCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelInviteCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelInviteCodeUpsert) {
//			SetBatchID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelInviteCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelInviteCodeUpsertBulk {
	_c.conflict = opts
	return &ChannelInviteCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelInviteCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelInviteCodeCreateBulk) OnConflictColumns(columns ...string) *ChannelInviteCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelInviteCodeUpsertBulk{
		create: _c,
	}
}

// ChannelInviteCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of ChannelInviteCode nodes.
type ChannelInviteCodeUpsertBulk struct {
	create *ChannelInviteCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChannelInviteCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelInviteCodeUpsertBulk) UpdateNewValues() *ChannelInviteCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(channelinvitecode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelInviteCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelInviteCodeUpsertBulk) Ignore() *ChannelInviteCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelInviteCodeUpsertBulk) DoNothing() *ChannelInviteCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelInviteCodeCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelInviteCodeUpsertBulk) Update(set func(*ChannelInviteCodeUpsert)) *ChannelInviteCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelInviteCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *ChannelInviteCodeUpsertBulk) SetBatchID(v int64) *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsertBulk) UpdateBatchID() *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.UpdateBatchID()
	})
}

// SetCode sets the "code" field.
func (u *ChannelInviteCodeUpsertBulk) SetCode(v string) *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsertBulk) UpdateCode() *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.UpdateCode()
	})
}

// SetStatus sets the "status" field.
func (u *ChannelInviteCodeUpsertBulk) SetStatus(v string) *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsertBulk) UpdateStatus() *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.UpdateStatus()
	})
}

// SetMaxUses sets the "max_uses" field.
func (u *ChannelInviteCodeUpsertBulk) SetMaxUses(v int) *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.SetMaxUses(v)
	})
}

// AddMaxUses adds v to the "max_uses" field.
func (u *ChannelInviteCodeUpsertBulk) AddMaxUses(v int) *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.AddMaxUses(v)
	})
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsertBulk) UpdateMaxUses() *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.UpdateMaxUses()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *ChannelInviteCodeUpsertBulk) SetUsedCount(v int) *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *ChannelInviteCodeUpsertBulk) AddUsedCount(v int) *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsertBulk) UpdateUsedCount() *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.UpdateUsedCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelInviteCodeUpsertBulk) SetUpdatedAt(v time.Time) *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelInviteCodeUpsertBulk) UpdateUpdatedAt() *ChannelInviteCodeUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChannelInviteCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelInviteCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelInviteCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelInviteCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
