// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecode"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecodeusage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChannelInviteCodeQuery is the builder for querying ChannelInviteCode entities.
type ChannelInviteCodeQuery struct {
	config
	ctx        *QueryContext
	order      []channelinvitecode.OrderOption
	inters     []Interceptor
	predicates []predicate.ChannelInviteCode
	withBatch  *ChannelInviteBatchQuery
	withUsages *ChannelInviteCodeUsageQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChannelInviteCodeQuery builder.
func (_q *ChannelInviteCodeQuery) Where(ps ...predicate.ChannelInviteCode) *ChannelInviteCodeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChannelInviteCodeQuery) Limit(limit int) *ChannelInviteCodeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChannelInviteCodeQuery) Offset(offset int) *ChannelInviteCodeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChannelInviteCodeQuery) Unique(unique bool) *ChannelInviteCodeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChannelInviteCodeQuery) Order(o ...channelinvitecode.OrderOption) *ChannelInviteCodeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryBatch chains the current query on the "batch" edge.
func (_q *ChannelInviteCodeQuery) QueryBatch() *ChannelInviteBatchQuery {
	query := (&ChannelInviteBatchClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channelinvitecode.Table, channelinvitecode.FieldID, selector),
			sqlgraph.To(channelinvitebatch.Table, channelinvitebatch.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, channelinvitecode.BatchTable, channelinvitecode.BatchColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsages chains the current query on the "usages" edge.
func (_q *ChannelInviteCodeQuery) QueryUsages() *ChannelInviteCodeUsageQuery {
	query := (&ChannelInviteCodeUsageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channelinvitecode.Table, channelinvitecode.FieldID, selector),
			sqlgraph.To(channelinvitecodeusage.Table, channelinvitecodeusage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channelinvitecode.UsagesTable, channelinvitecode.UsagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChannelInviteCode entity from the query.
// Returns a *NotFoundError when no ChannelInviteCode was found.
func (_q *ChannelInviteCodeQuery) First(ctx context.Context) (*ChannelInviteCode, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{channelinvitecode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChannelInviteCodeQuery) FirstX(ctx context.Context) *ChannelInviteCode {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChannelInviteCode ID from the query.
// Returns a *NotFoundError when no ChannelInviteCode ID was found.
func (_q *ChannelInviteCodeQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{channelinvitecode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChannelInviteCodeQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChannelInviteCode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChannelInviteCode entity is found.
// Returns a *NotFoundError when no ChannelInviteCode entities are found.
func (_q *ChannelInviteCodeQuery) Only(ctx context.Context) (*ChannelInviteCode, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{channelinvitecode.Label}
	default:
		return nil, &NotSingularError{channelinvitecode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChannelInviteCodeQuery) OnlyX(ctx context.Context) *ChannelInviteCode {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChannelInviteCode ID in the query.
// Returns a *NotSingularError when more than one ChannelInviteCode ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChannelInviteCodeQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{channelinvitecode.Label}
	default:
		err = &NotSingularError{channelinvitecode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChannelInviteCodeQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChannelInviteCodes.
func (_q *ChannelInviteCodeQuery) All(ctx context.Context) ([]*ChannelInviteCode, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChannelInviteCode, *ChannelInviteCodeQuery]()
	return withInterceptors[[]*ChannelInviteCode](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChannelInviteCodeQuery) AllX(ctx context.Context) []*ChannelInviteCode {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChannelInviteCode IDs.
func (_q *ChannelInviteCodeQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(channelinvitecode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChannelInviteCodeQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChannelInviteCodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChannelInviteCodeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChannelInviteCodeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChannelInviteCodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChannelInviteCodeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChannelInviteCodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChannelInviteCodeQuery) Clone() *ChannelInviteCodeQuery {
	if _q == nil {
		return nil
	}
	return &ChannelInviteCodeQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]channelinvitecode.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.ChannelInviteCode{}, _q.predicates...),
		withBatch:  _q.withBatch.Clone(),
		withUsages: _q.withUsages.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithBatch tells the query-builder to eager-load the nodes that are connected to
// the "batch" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelInviteCodeQuery) WithBatch(opts ...func(*ChannelInviteBatchQuery)) *ChannelInviteCodeQuery {
	query := (&ChannelInviteBatchClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBatch = query
	return _q
}

// WithUsages tells the query-builder to eager-load the nodes that are connected to
// the "usages" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelInviteCodeQuery) WithUsages(opts ...func(*ChannelInviteCodeUsageQuery)) *ChannelInviteCodeQuery {
	query := (&ChannelInviteCodeUsageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUsages = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BatchID int64 `json:"batch_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChannelInviteCode.Query().
//		GroupBy(channelinvitecode.FieldBatchID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChannelInviteCodeQuery) GroupBy(field string, fields ...string) *ChannelInviteCodeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChannelInviteCodeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = channelinvitecode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BatchID int64 `json:"batch_id,omitempty"`
//	}
//
//	client.ChannelInviteCode.Query().
//		Select(channelinvitecode.FieldBatchID).
//		Scan(ctx, &v)
func (_q *ChannelInviteCodeQuery) Select(fields ...string) *ChannelInviteCodeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChannelInviteCodeSelect{ChannelInviteCodeQuery: _q}
	sbuild.label = channelinvitecode.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChannelInviteCodeSelect configured with the given aggregations.
func (_q *ChannelInviteCodeQuery) Aggregate(fns ...AggregateFunc) *ChannelInviteCodeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChannelInviteCodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !channelinvitecode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChannelInviteCodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChannelInviteCode, error) {
	var (
		nodes       = []*ChannelInviteCode{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withBatch != nil,
			_q.withUsages != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChannelInviteCode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChannelInviteCode{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withBatch; query != nil {
		if err := _q.loadBatch(ctx, query, nodes, nil,
			func(n *ChannelInviteCode, e *ChannelInviteBatch) { n.Edges.Batch = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUsages; query != nil {
		if err := _q.loadUsages(ctx, query, nodes,
			func(n *ChannelInviteCode) { n.Edges.Usages = []*ChannelInviteCodeUsage{} },
			func(n *ChannelInviteCode, e *ChannelInviteCodeUsage) { n.Edges.Usages = append(n.Edges.Usages, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChannelInviteCodeQuery) loadBatch(ctx context.Context, query *ChannelInviteBatchQuery, nodes []*ChannelInviteCode, init func(*ChannelInviteCode), assign func(*ChannelInviteCode, *ChannelInviteBatch)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ChannelInviteCode)
	for i := range nodes {
		fk := nodes[i].BatchID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(channelinvitebatch.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "batch_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ChannelInviteCodeQuery) loadUsages(ctx context.Context, query *ChannelInviteCodeUsageQuery, nodes []*ChannelInviteCode, init func(*ChannelInviteCode), assign func(*ChannelInviteCode, *ChannelInviteCodeUsage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*ChannelInviteCode)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(channelinvitecodeusage.FieldCodeID)
	}
	query.Where(predicate.ChannelInviteCodeUsage(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(channelinvitecode.UsagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CodeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "code_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ChannelInviteCodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChannelInviteCodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(channelinvitecode.Table, channelinvitecode.Columns, sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelinvitecode.FieldID)
		for i := range fields {
			if fields[i] != channelinvitecode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withBatch != nil {
			_spec.Node.AddColumnOnce(channelinvitecode.FieldBatchID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChannelInviteCodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(channelinvitecode.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = channelinvitecode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ChannelInviteCodeQuery) ForUpdate(opts ...sql.LockOption) *ChannelInviteCodeQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ChannelInviteCodeQuery) ForShare(opts ...sql.LockOption) *ChannelInviteCodeQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ChannelInviteCodeGroupBy is the group-by builder for ChannelInviteCode entities.
type ChannelInviteCodeGroupBy struct {
	selector
	build *ChannelInviteCodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChannelInviteCodeGroupBy) Aggregate(fns ...AggregateFunc) *ChannelInviteCodeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChannelInviteCodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChannelInviteCodeQuery, *ChannelInviteCodeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChannelInviteCodeGroupBy) sqlScan(ctx context.Context, root *ChannelInviteCodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChannelInviteCodeSelect is the builder for selecting fields of ChannelInviteCode entities.
type ChannelInviteCodeSelect struct {
	*ChannelInviteCodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChannelInviteCodeSelect) Aggregate(fns ...AggregateFunc) *ChannelInviteCodeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChannelInviteCodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChannelInviteCodeQuery, *ChannelInviteCodeSelect](ctx, _s.ChannelInviteCodeQuery, _s, _s.inters, v)
}

func (_s *ChannelInviteCodeSelect) sqlScan(ctx context.Context, root *ChannelInviteCodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
