// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatchgroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChannelInviteBatchGroupQuery is the builder for querying ChannelInviteBatchGroup entities.
type ChannelInviteBatchGroupQuery struct {
	config
	ctx        *QueryContext
	order      []channelinvitebatchgroup.OrderOption
	inters     []Interceptor
	predicates []predicate.ChannelInviteBatchGroup
	withBatch  *ChannelInviteBatchQuery
	withGroup  *GroupQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChannelInviteBatchGroupQuery builder.
func (_q *ChannelInviteBatchGroupQuery) Where(ps ...predicate.ChannelInviteBatchGroup) *ChannelInviteBatchGroupQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChannelInviteBatchGroupQuery) Limit(limit int) *ChannelInviteBatchGroupQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChannelInviteBatchGroupQuery) Offset(offset int) *ChannelInviteBatchGroupQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChannelInviteBatchGroupQuery) Unique(unique bool) *ChannelInviteBatchGroupQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChannelInviteBatchGroupQuery) Order(o ...channelinvitebatchgroup.OrderOption) *ChannelInviteBatchGroupQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryBatch chains the current query on the "batch" edge.
func (_q *ChannelInviteBatchGroupQuery) QueryBatch() *ChannelInviteBatchQuery {
	query := (&ChannelInviteBatchClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channelinvitebatchgroup.Table, channelinvitebatchgroup.FieldID, selector),
			sqlgraph.To(channelinvitebatch.Table, channelinvitebatch.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, channelinvitebatchgroup.BatchTable, channelinvitebatchgroup.BatchColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (_q *ChannelInviteBatchGroupQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channelinvitebatchgroup.Table, channelinvitebatchgroup.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, channelinvitebatchgroup.GroupTable, channelinvitebatchgroup.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChannelInviteBatchGroup entity from the query.
// Returns a *NotFoundError when no ChannelInviteBatchGroup was found.
func (_q *ChannelInviteBatchGroupQuery) First(ctx context.Context) (*ChannelInviteBatchGroup, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{channelinvitebatchgroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChannelInviteBatchGroupQuery) FirstX(ctx context.Context) *ChannelInviteBatchGroup {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChannelInviteBatchGroup ID from the query.
// Returns a *NotFoundError when no ChannelInviteBatchGroup ID was found.
func (_q *ChannelInviteBatchGroupQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{channelinvitebatchgroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChannelInviteBatchGroupQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChannelInviteBatchGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChannelInviteBatchGroup entity is found.
// Returns a *NotFoundError when no ChannelInviteBatchGroup entities are found.
func (_q *ChannelInviteBatchGroupQuery) Only(ctx context.Context) (*ChannelInviteBatchGroup, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{channelinvitebatchgroup.Label}
	default:
		return nil, &NotSingularError{channelinvitebatchgroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChannelInviteBatchGroupQuery) OnlyX(ctx context.Context) *ChannelInviteBatchGroup {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChannelInviteBatchGroup ID in the query.
// Returns a *NotSingularError when more than one ChannelInviteBatchGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChannelInviteBatchGroupQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{channelinvitebatchgroup.Label}
	default:
		err = &NotSingularError{channelinvitebatchgroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChannelInviteBatchGroupQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChannelInviteBatchGroups.
func (_q *ChannelInviteBatchGroupQuery) All(ctx context.Context) ([]*ChannelInviteBatchGroup, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChannelInviteBatchGroup, *ChannelInviteBatchGroupQuery]()
	return withInterceptors[[]*ChannelInviteBatchGroup](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChannelInviteBatchGroupQuery) AllX(ctx context.Context) []*ChannelInviteBatchGroup {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChannelInviteBatchGroup IDs.
func (_q *ChannelInviteBatchGroupQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(channelinvitebatchgroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChannelInviteBatchGroupQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChannelInviteBatchGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChannelInviteBatchGroupQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChannelInviteBatchGroupQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChannelInviteBatchGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChannelInviteBatchGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChannelInviteBatchGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChannelInviteBatchGroupQuery) Clone() *ChannelInviteBatchGroupQuery {
	if _q == nil {
		return nil
	}
	return &ChannelInviteBatchGroupQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]channelinvitebatchgroup.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.ChannelInviteBatchGroup{}, _q.predicates...),
		withBatch:  _q.withBatch.Clone(),
		withGroup:  _q.withGroup.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithBatch tells the query-builder to eager-load the nodes that are connected to
// the "batch" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelInviteBatchGroupQuery) WithBatch(opts ...func(*ChannelInviteBatchQuery)) *ChannelInviteBatchGroupQuery {
	query := (&ChannelInviteBatchClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBatch = query
	return _q
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelInviteBatchGroupQuery) WithGroup(opts ...func(*GroupQuery)) *ChannelInviteBatchGroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BatchID int64 `json:"batch_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChannelInviteBatchGroup.Query().
//		GroupBy(channelinvitebatchgroup.FieldBatchID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChannelInviteBatchGroupQuery) GroupBy(field string, fields ...string) *ChannelInviteBatchGroupGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChannelInviteBatchGroupGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = channelinvitebatchgroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BatchID int64 `json:"batch_id,omitempty"`
//	}
//
//	client.ChannelInviteBatchGroup.Query().
//		Select(channelinvitebatchgroup.FieldBatchID).
//		Scan(ctx, &v)
func (_q *ChannelInviteBatchGroupQuery) Select(fields ...string) *ChannelInviteBatchGroupSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChannelInviteBatchGroupSelect{ChannelInviteBatchGroupQuery: _q}
	sbuild.label = channelinvitebatchgroup.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChannelInviteBatchGroupSelect configured with the given aggregations.
func (_q *ChannelInviteBatchGroupQuery) Aggregate(fns ...AggregateFunc) *ChannelInviteBatchGroupSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChannelInviteBatchGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !channelinvitebatchgroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChannelInviteBatchGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChannelInviteBatchGroup, error) {
	var (
		nodes       = []*ChannelInviteBatchGroup{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withBatch != nil,
			_q.withGroup != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChannelInviteBatchGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChannelInviteBatchGroup{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withBatch; query != nil {
		if err := _q.loadBatch(ctx, query, nodes, nil,
			func(n *ChannelInviteBatchGroup, e *ChannelInviteBatch) { n.Edges.Batch = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *ChannelInviteBatchGroup, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChannelInviteBatchGroupQuery) loadBatch(ctx context.Context, query *ChannelInviteBatchQuery, nodes []*ChannelInviteBatchGroup, init func(*ChannelInviteBatchGroup), assign func(*ChannelInviteBatchGroup, *ChannelInviteBatch)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ChannelInviteBatchGroup)
	for i := range nodes {
		fk := nodes[i].BatchID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(channelinvitebatch.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "batch_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ChannelInviteBatchGroupQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*ChannelInviteBatchGroup, init func(*ChannelInviteBatchGroup), assign func(*ChannelInviteBatchGroup, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ChannelInviteBatchGroup)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ChannelInviteBatchGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChannelInviteBatchGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(channelinvitebatchgroup.Table, channelinvitebatchgroup.Columns, sqlgraph.NewFieldSpec(channelinvitebatchgroup.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelinvitebatchgroup.FieldID)
		for i := range fields {
			if fields[i] != channelinvitebatchgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withBatch != nil {
			_spec.Node.AddColumnOnce(channelinvitebatchgroup.FieldBatchID)
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(channelinvitebatchgroup.FieldGroupID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChannelInviteBatchGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(channelinvitebatchgroup.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = channelinvitebatchgroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *ChannelInviteBatchGroupQuery) ForUpdate(opts ...sql.LockOption) *ChannelInviteBatchGroupQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *ChannelInviteBatchGroupQuery) ForShare(opts ...sql.LockOption) *ChannelInviteBatchGroupQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// ChannelInviteBatchGroupGroupBy is the group-by builder for ChannelInviteBatchGroup entities.
type ChannelInviteBatchGroupGroupBy struct {
	selector
	build *ChannelInviteBatchGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChannelInviteBatchGroupGroupBy) Aggregate(fns ...AggregateFunc) *ChannelInviteBatchGroupGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChannelInviteBatchGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChannelInviteBatchGroupQuery, *ChannelInviteBatchGroupGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChannelInviteBatchGroupGroupBy) sqlScan(ctx context.Context, root *ChannelInviteBatchGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChannelInviteBatchGroupSelect is the builder for selecting fields of ChannelInviteBatchGroup entities.
type ChannelInviteBatchGroupSelect struct {
	*ChannelInviteBatchGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChannelInviteBatchGroupSelect) Aggregate(fns ...AggregateFunc) *ChannelInviteBatchGroupSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChannelInviteBatchGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChannelInviteBatchGroupQuery, *ChannelInviteBatchGroupSelect](ctx, _s.ChannelInviteBatchGroupQuery, _s, _s.inters, v)
}

func (_s *ChannelInviteBatchGroupSelect) sqlScan(ctx context.Context, root *ChannelInviteBatchGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
