// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecode"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChannelInviteCodeDelete is the builder for deleting a ChannelInviteCode entity.
type ChannelInviteCodeDelete struct {
	config
	hooks    []Hook
	mutation *ChannelInviteCodeMutation
}

// Where appends a list predicates to the ChannelInviteCodeDelete builder.
func (_d *ChannelInviteCodeDelete) Where(ps ...predicate.ChannelInviteCode) *ChannelInviteCodeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChannelInviteCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelInviteCodeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChannelInviteCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(channelinvitecode.Table, sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChannelInviteCodeDeleteOne is the builder for deleting a single ChannelInviteCode entity.
type ChannelInviteCodeDeleteOne struct {
	_d *ChannelInviteCodeDelete
}

// Where appends a list predicates to the ChannelInviteCodeDelete builder.
func (_d *ChannelInviteCodeDeleteOne) Where(ps ...predicate.ChannelInviteCode) *ChannelInviteCodeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChannelInviteCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{channelinvitecode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelInviteCodeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
