// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatchgroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChannelInviteBatchGroupUpdate is the builder for updating ChannelInviteBatchGroup entities.
type ChannelInviteBatchGroupUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelInviteBatchGroupMutation
}

// Where appends a list predicates to the ChannelInviteBatchGroupUpdate builder.
func (_u *ChannelInviteBatchGroupUpdate) Where(ps ...predicate.ChannelInviteBatchGroup) *ChannelInviteBatchGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *ChannelInviteBatchGroupUpdate) SetBatchID(v int64) *ChannelInviteBatchGroupUpdate {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *ChannelInviteBatchGroupUpdate) SetNillableBatchID(v *int64) *ChannelInviteBatchGroupUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ChannelInviteBatchGroupUpdate) SetGroupID(v int64) *ChannelInviteBatchGroupUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ChannelInviteBatchGroupUpdate) SetNillableGroupID(v *int64) *ChannelInviteBatchGroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetBatch sets the "batch" edge to the ChannelInviteBatch entity.
func (_u *ChannelInviteBatchGroupUpdate) SetBatch(v *ChannelInviteBatch) *ChannelInviteBatchGroupUpdate {
	return _u.SetBatchID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *ChannelInviteBatchGroupUpdate) SetGroup(v *Group) *ChannelInviteBatchGroupUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the ChannelInviteBatchGroupMutation object of the builder.
func (_u *ChannelInviteBatchGroupUpdate) Mutation() *ChannelInviteBatchGroupMutation {
	return _u.mutation
}

// ClearBatch clears the "batch" edge to the ChannelInviteBatch entity.
func (_u *ChannelInviteBatchGroupUpdate) ClearBatch() *ChannelInviteBatchGroupUpdate {
	_u.mutation.ClearBatch()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *ChannelInviteBatchGroupUpdate) ClearGroup() *ChannelInviteBatchGroupUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelInviteBatchGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelInviteBatchGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelInviteBatchGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelInviteBatchGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelInviteBatchGroupUpdate) check() error {
	if _u.mutation.BatchCleared() && len(_u.mutation.BatchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteBatchGroup.batch"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteBatchGroup.group"`)
	}
	return nil
}

func (_u *ChannelInviteBatchGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelinvitebatchgroup.Table, channelinvitebatchgroup.Columns, sqlgraph.NewFieldSpec(channelinvitebatchgroup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.BatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatchgroup.BatchTable,
			Columns: []string{channelinvitebatchgroup.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatchgroup.BatchTable,
			Columns: []string{channelinvitebatchgroup.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatchgroup.GroupTable,
			Columns: []string{channelinvitebatchgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatchgroup.GroupTable,
			Columns: []string{channelinvitebatchgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelinvitebatchgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelInviteBatchGroupUpdateOne is the builder for updating a single ChannelInviteBatchGroup entity.
type ChannelInviteBatchGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelInviteBatchGroupMutation
}

// SetBatchID sets the "batch_id" field.
func (_u *ChannelInviteBatchGroupUpdateOne) SetBatchID(v int64) *ChannelInviteBatchGroupUpdateOne {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *ChannelInviteBatchGroupUpdateOne) SetNillableBatchID(v *int64) *ChannelInviteBatchGroupUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ChannelInviteBatchGroupUpdateOne) SetGroupID(v int64) *ChannelInviteBatchGroupUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ChannelInviteBatchGroupUpdateOne) SetNillableGroupID(v *int64) *ChannelInviteBatchGroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetBatch sets the "batch" edge to the ChannelInviteBatch entity.
func (_u *ChannelInviteBatchGroupUpdateOne) SetBatch(v *ChannelInviteBatch) *ChannelInviteBatchGroupUpdateOne {
	return _u.SetBatchID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *ChannelInviteBatchGroupUpdateOne) SetGroup(v *Group) *ChannelInviteBatchGroupUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the ChannelInviteBatchGroupMutation object of the builder.
func (_u *ChannelInviteBatchGroupUpdateOne) Mutation() *ChannelInviteBatchGroupMutation {
	return _u.mutation
}

// ClearBatch clears the "batch" edge to the ChannelInviteBatch entity.
func (_u *ChannelInviteBatchGroupUpdateOne) ClearBatch() *ChannelInviteBatchGroupUpdateOne {
	_u.mutation.ClearBatch()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *ChannelInviteBatchGroupUpdateOne) ClearGroup() *ChannelInviteBatchGroupUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the ChannelInviteBatchGroupUpdate builder.
func (_u *ChannelInviteBatchGroupUpdateOne) Where(ps ...predicate.ChannelInviteBatchGroup) *ChannelInviteBatchGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelInviteBatchGroupUpdateOne) Select(field string, fields ...string) *ChannelInviteBatchGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelInviteBatchGroup entity.
func (_u *ChannelInviteBatchGroupUpdateOne) Save(ctx context.Context) (*ChannelInviteBatchGroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelInviteBatchGroupUpdateOne) SaveX(ctx context.Context) *ChannelInviteBatchGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelInviteBatchGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelInviteBatchGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelInviteBatchGroupUpdateOne) check() error {
	if _u.mutation.BatchCleared() && len(_u.mutation.BatchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteBatchGroup.batch"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteBatchGroup.group"`)
	}
	return nil
}

func (_u *ChannelInviteBatchGroupUpdateOne) sqlSave(ctx context.Context) (_node *ChannelInviteBatchGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelinvitebatchgroup.Table, channelinvitebatchgroup.Columns, sqlgraph.NewFieldSpec(channelinvitebatchgroup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelInviteBatchGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelinvitebatchgroup.FieldID)
		for _, f := range fields {
			if !channelinvitebatchgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelinvitebatchgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.BatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatchgroup.BatchTable,
			Columns: []string{channelinvitebatchgroup.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatchgroup.BatchTable,
			Columns: []string{channelinvitebatchgroup.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatchgroup.GroupTable,
			Columns: []string{channelinvitebatchgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatchgroup.GroupTable,
			Columns: []string{channelinvitebatchgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChannelInviteBatchGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelinvitebatchgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
