// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecode"
)

// ChannelInviteCode is the model entity for the ChannelInviteCode schema.
type ChannelInviteCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 所属批次ID
	BatchID int64 `json:"batch_id,omitempty"`
	// 邀请码
	Code string `json:"code,omitempty"`
	// 状态: unused, used, expired
	Status string `json:"status,omitempty"`
	// 最大使用次数
	MaxUses int `json:"max_uses,omitempty"`
	// 已使用次数
	UsedCount int `json:"used_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChannelInviteCodeQuery when eager-loading is set.
	Edges        ChannelInviteCodeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChannelInviteCodeEdges holds the relations/edges for other nodes in the graph.
type ChannelInviteCodeEdges struct {
	// Batch holds the value of the batch edge.
	Batch *ChannelInviteBatch `json:"batch,omitempty"`
	// Usages holds the value of the usages edge.
	Usages []*ChannelInviteCodeUsage `json:"usages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BatchOrErr returns the Batch value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelInviteCodeEdges) BatchOrErr() (*ChannelInviteBatch, error) {
	if e.Batch != nil {
		return e.Batch, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channelinvitebatch.Label}
	}
	return nil, &NotLoadedError{edge: "batch"}
}

// UsagesOrErr returns the Usages value or an error if the edge
// was not loaded in eager-loading.
func (e ChannelInviteCodeEdges) UsagesOrErr() ([]*ChannelInviteCodeUsage, error) {
	if e.loadedTypes[1] {
		return e.Usages, nil
	}
	return nil, &NotLoadedError{edge: "usages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelInviteCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelinvitecode.FieldID, channelinvitecode.FieldBatchID, channelinvitecode.FieldMaxUses, channelinvitecode.FieldUsedCount:
			values[i] = new(sql.NullInt64)
		case channelinvitecode.FieldCode, channelinvitecode.FieldStatus:
			values[i] = new(sql.NullString)
		case channelinvitecode.FieldCreatedAt, channelinvitecode.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelInviteCode fields.
func (_m *ChannelInviteCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelinvitecode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case channelinvitecode.FieldBatchID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field batch_id", values[i])
			} else if value.Valid {
				_m.BatchID = value.Int64
			}
		case channelinvitecode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case channelinvitecode.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case channelinvitecode.FieldMaxUses:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_uses", values[i])
			} else if value.Valid {
				_m.MaxUses = int(value.Int64)
			}
		case channelinvitecode.FieldUsedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field used_count", values[i])
			} else if value.Valid {
				_m.UsedCount = int(value.Int64)
			}
		case channelinvitecode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case channelinvitecode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelInviteCode.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelInviteCode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBatch queries the "batch" edge of the ChannelInviteCode entity.
func (_m *ChannelInviteCode) QueryBatch() *ChannelInviteBatchQuery {
	return NewChannelInviteCodeClient(_m.config).QueryBatch(_m)
}

// QueryUsages queries the "usages" edge of the ChannelInviteCode entity.
func (_m *ChannelInviteCode) QueryUsages() *ChannelInviteCodeUsageQuery {
	return NewChannelInviteCodeClient(_m.config).QueryUsages(_m)
}

// Update returns a builder for updating this ChannelInviteCode.
// Note that you need to call ChannelInviteCode.Unwrap() before calling this method if this ChannelInviteCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelInviteCode) Update() *ChannelInviteCodeUpdateOne {
	return NewChannelInviteCodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelInviteCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelInviteCode) Unwrap() *ChannelInviteCode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelInviteCode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelInviteCode) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelInviteCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("batch_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BatchID))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("max_uses=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxUses))
	builder.WriteString(", ")
	builder.WriteString("used_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelInviteCodes is a parsable slice of ChannelInviteCode.
type ChannelInviteCodes []*ChannelInviteCode
