// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecode"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecodeusage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChannelInviteCodeUpdate is the builder for updating ChannelInviteCode entities.
type ChannelInviteCodeUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelInviteCodeMutation
}

// Where appends a list predicates to the ChannelInviteCodeUpdate builder.
func (_u *ChannelInviteCodeUpdate) Where(ps ...predicate.ChannelInviteCode) *ChannelInviteCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *ChannelInviteCodeUpdate) SetBatchID(v int64) *ChannelInviteCodeUpdate {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *ChannelInviteCodeUpdate) SetNillableBatchID(v *int64) *ChannelInviteCodeUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *ChannelInviteCodeUpdate) SetCode(v string) *ChannelInviteCodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ChannelInviteCodeUpdate) SetNillableCode(v *string) *ChannelInviteCodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChannelInviteCodeUpdate) SetStatus(v string) *ChannelInviteCodeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChannelInviteCodeUpdate) SetNillableStatus(v *string) *ChannelInviteCodeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *ChannelInviteCodeUpdate) SetMaxUses(v int) *ChannelInviteCodeUpdate {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *ChannelInviteCodeUpdate) SetNillableMaxUses(v *int) *ChannelInviteCodeUpdate {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *ChannelInviteCodeUpdate) AddMaxUses(v int) *ChannelInviteCodeUpdate {
	_u.mutation.AddMaxUses(v)
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *ChannelInviteCodeUpdate) SetUsedCount(v int) *ChannelInviteCodeUpdate {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *ChannelInviteCodeUpdate) SetNillableUsedCount(v *int) *ChannelInviteCodeUpdate {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *ChannelInviteCodeUpdate) AddUsedCount(v int) *ChannelInviteCodeUpdate {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelInviteCodeUpdate) SetUpdatedAt(v time.Time) *ChannelInviteCodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBatch sets the "batch" edge to the ChannelInviteBatch entity.
func (_u *ChannelInviteCodeUpdate) SetBatch(v *ChannelInviteBatch) *ChannelInviteCodeUpdate {
	return _u.SetBatchID(v.ID)
}

// AddUsageIDs adds the "usages" edge to the ChannelInviteCodeUsage entity by IDs.
func (_u *ChannelInviteCodeUpdate) AddUsageIDs(ids ...int64) *ChannelInviteCodeUpdate {
	_u.mutation.AddUsageIDs(ids...)
	return _u
}

// AddUsages adds the "usages" edges to the ChannelInviteCodeUsage entity.
func (_u *ChannelInviteCodeUpdate) AddUsages(v ...*ChannelInviteCodeUsage) *ChannelInviteCodeUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageIDs(ids...)
}

// Mutation returns the ChannelInviteCodeMutation object of the builder.
func (_u *ChannelInviteCodeUpdate) Mutation() *ChannelInviteCodeMutation {
	return _u.mutation
}

// ClearBatch clears the "batch" edge to the ChannelInviteBatch entity.
func (_u *ChannelInviteCodeUpdate) ClearBatch() *ChannelInviteCodeUpdate {
	_u.mutation.ClearBatch()
	return _u
}

// ClearUsages clears all "usages" edges to the ChannelInviteCodeUsage entity.
func (_u *ChannelInviteCodeUpdate) ClearUsages() *ChannelInviteCodeUpdate {
	_u.mutation.ClearUsages()
	return _u
}

// RemoveUsageIDs removes the "usages" edge to ChannelInviteCodeUsage entities by IDs.
func (_u *ChannelInviteCodeUpdate) RemoveUsageIDs(ids ...int64) *ChannelInviteCodeUpdate {
	_u.mutation.RemoveUsageIDs(ids...)
	return _u
}

// RemoveUsages removes "usages" edges to ChannelInviteCodeUsage entities.
func (_u *ChannelInviteCodeUpdate) RemoveUsages(v ...*ChannelInviteCodeUsage) *ChannelInviteCodeUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelInviteCodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelInviteCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelInviteCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelInviteCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelInviteCodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channelinvitecode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelInviteCodeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := channelinvitecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ChannelInviteCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := channelinvitecode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChannelInviteCode.status": %w`, err)}
		}
	}
	if _u.mutation.BatchCleared() && len(_u.mutation.BatchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteCode.batch"`)
	}
	return nil
}

func (_u *ChannelInviteCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelinvitecode.Table, channelinvitecode.Columns, sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(channelinvitecode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(channelinvitecode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(channelinvitecode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(channelinvitecode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(channelinvitecode.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(channelinvitecode.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelinvitecode.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecode.BatchTable,
			Columns: []string{channelinvitecode.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecode.BatchTable,
			Columns: []string{channelinvitecode.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitecode.UsagesTable,
			Columns: []string{channelinvitecode.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsagesIDs(); len(nodes) > 0 && !_u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitecode.UsagesTable,
			Columns: []string{channelinvitecode.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitecode.UsagesTable,
			Columns: []string{channelinvitecode.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelinvitecode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelInviteCodeUpdateOne is the builder for updating a single ChannelInviteCode entity.
type ChannelInviteCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelInviteCodeMutation
}

// SetBatchID sets the "batch_id" field.
func (_u *ChannelInviteCodeUpdateOne) SetBatchID(v int64) *ChannelInviteCodeUpdateOne {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *ChannelInviteCodeUpdateOne) SetNillableBatchID(v *int64) *ChannelInviteCodeUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *ChannelInviteCodeUpdateOne) SetCode(v string) *ChannelInviteCodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ChannelInviteCodeUpdateOne) SetNillableCode(v *string) *ChannelInviteCodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChannelInviteCodeUpdateOne) SetStatus(v string) *ChannelInviteCodeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChannelInviteCodeUpdateOne) SetNillableStatus(v *string) *ChannelInviteCodeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMaxUses sets the "max_uses" field.
func (_u *ChannelInviteCodeUpdateOne) SetMaxUses(v int) *ChannelInviteCodeUpdateOne {
	_u.mutation.ResetMaxUses()
	_u.mutation.SetMaxUses(v)
	return _u
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_u *ChannelInviteCodeUpdateOne) SetNillableMaxUses(v *int) *ChannelInviteCodeUpdateOne {
	if v != nil {
		_u.SetMaxUses(*v)
	}
	return _u
}

// AddMaxUses adds value to the "max_uses" field.
func (_u *ChannelInviteCodeUpdateOne) AddMaxUses(v int) *ChannelInviteCodeUpdateOne {
	_u.mutation.AddMaxUses(v)
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *ChannelInviteCodeUpdateOne) SetUsedCount(v int) *ChannelInviteCodeUpdateOne {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *ChannelInviteCodeUpdateOne) SetNillableUsedCount(v *int) *ChannelInviteCodeUpdateOne {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *ChannelInviteCodeUpdateOne) AddUsedCount(v int) *ChannelInviteCodeUpdateOne {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelInviteCodeUpdateOne) SetUpdatedAt(v time.Time) *ChannelInviteCodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBatch sets the "batch" edge to the ChannelInviteBatch entity.
func (_u *ChannelInviteCodeUpdateOne) SetBatch(v *ChannelInviteBatch) *ChannelInviteCodeUpdateOne {
	return _u.SetBatchID(v.ID)
}

// AddUsageIDs adds the "usages" edge to the ChannelInviteCodeUsage entity by IDs.
func (_u *ChannelInviteCodeUpdateOne) AddUsageIDs(ids ...int64) *ChannelInviteCodeUpdateOne {
	_u.mutation.AddUsageIDs(ids...)
	return _u
}

// AddUsages adds the "usages" edges to the ChannelInviteCodeUsage entity.
func (_u *ChannelInviteCodeUpdateOne) AddUsages(v ...*ChannelInviteCodeUsage) *ChannelInviteCodeUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageIDs(ids...)
}

// Mutation returns the ChannelInviteCodeMutation object of the builder.
func (_u *ChannelInviteCodeUpdateOne) Mutation() *ChannelInviteCodeMutation {
	return _u.mutation
}

// ClearBatch clears the "batch" edge to the ChannelInviteBatch entity.
func (_u *ChannelInviteCodeUpdateOne) ClearBatch() *ChannelInviteCodeUpdateOne {
	_u.mutation.ClearBatch()
	return _u
}

// ClearUsages clears all "usages" edges to the ChannelInviteCodeUsage entity.
func (_u *ChannelInviteCodeUpdateOne) ClearUsages() *ChannelInviteCodeUpdateOne {
	_u.mutation.ClearUsages()
	return _u
}

// RemoveUsageIDs removes the "usages" edge to ChannelInviteCodeUsage entities by IDs.
func (_u *ChannelInviteCodeUpdateOne) RemoveUsageIDs(ids ...int64) *ChannelInviteCodeUpdateOne {
	_u.mutation.RemoveUsageIDs(ids...)
	return _u
}

// RemoveUsages removes "usages" edges to ChannelInviteCodeUsage entities.
func (_u *ChannelInviteCodeUpdateOne) RemoveUsages(v ...*ChannelInviteCodeUsage) *ChannelInviteCodeUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageIDs(ids...)
}

// Where appends a list predicates to the ChannelInviteCodeUpdate builder.
func (_u *ChannelInviteCodeUpdateOne) Where(ps ...predicate.ChannelInviteCode) *ChannelInviteCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelInviteCodeUpdateOne) Select(field string, fields ...string) *ChannelInviteCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelInviteCode entity.
func (_u *ChannelInviteCodeUpdateOne) Save(ctx context.Context) (*ChannelInviteCode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelInviteCodeUpdateOne) SaveX(ctx context.Context) *ChannelInviteCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelInviteCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelInviteCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelInviteCodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channelinvitecode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelInviteCodeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := channelinvitecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ChannelInviteCode.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := channelinvitecode.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChannelInviteCode.status": %w`, err)}
		}
	}
	if _u.mutation.BatchCleared() && len(_u.mutation.BatchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteCode.batch"`)
	}
	return nil
}

func (_u *ChannelInviteCodeUpdateOne) sqlSave(ctx context.Context) (_node *ChannelInviteCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelinvitecode.Table, channelinvitecode.Columns, sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelInviteCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelinvitecode.FieldID)
		for _, f := range fields {
			if !channelinvitecode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelinvitecode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(channelinvitecode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(channelinvitecode.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxUses(); ok {
		_spec.SetField(channelinvitecode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUses(); ok {
		_spec.AddField(channelinvitecode.FieldMaxUses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(channelinvitecode.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(channelinvitecode.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelinvitecode.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecode.BatchTable,
			Columns: []string{channelinvitecode.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecode.BatchTable,
			Columns: []string{channelinvitecode.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitecode.UsagesTable,
			Columns: []string{channelinvitecode.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsagesIDs(); len(nodes) > 0 && !_u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitecode.UsagesTable,
			Columns: []string{channelinvitecode.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitecode.UsagesTable,
			Columns: []string{channelinvitecode.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChannelInviteCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelinvitecode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
