// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatchgroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// ChannelInviteBatchGroup is the model entity for the ChannelInviteBatchGroup schema.
type ChannelInviteBatchGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 批次ID
	BatchID int64 `json:"batch_id,omitempty"`
	// 分组ID
	GroupID int64 `json:"group_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChannelInviteBatchGroupQuery when eager-loading is set.
	Edges        ChannelInviteBatchGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChannelInviteBatchGroupEdges holds the relations/edges for other nodes in the graph.
type ChannelInviteBatchGroupEdges struct {
	// Batch holds the value of the batch edge.
	Batch *ChannelInviteBatch `json:"batch,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BatchOrErr returns the Batch value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelInviteBatchGroupEdges) BatchOrErr() (*ChannelInviteBatch, error) {
	if e.Batch != nil {
		return e.Batch, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channelinvitebatch.Label}
	}
	return nil, &NotLoadedError{edge: "batch"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelInviteBatchGroupEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelInviteBatchGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelinvitebatchgroup.FieldID, channelinvitebatchgroup.FieldBatchID, channelinvitebatchgroup.FieldGroupID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelInviteBatchGroup fields.
func (_m *ChannelInviteBatchGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelinvitebatchgroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case channelinvitebatchgroup.FieldBatchID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field batch_id", values[i])
			} else if value.Valid {
				_m.BatchID = value.Int64
			}
		case channelinvitebatchgroup.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelInviteBatchGroup.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelInviteBatchGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBatch queries the "batch" edge of the ChannelInviteBatchGroup entity.
func (_m *ChannelInviteBatchGroup) QueryBatch() *ChannelInviteBatchQuery {
	return NewChannelInviteBatchGroupClient(_m.config).QueryBatch(_m)
}

// QueryGroup queries the "group" edge of the ChannelInviteBatchGroup entity.
func (_m *ChannelInviteBatchGroup) QueryGroup() *GroupQuery {
	return NewChannelInviteBatchGroupClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this ChannelInviteBatchGroup.
// Note that you need to call ChannelInviteBatchGroup.Unwrap() before calling this method if this ChannelInviteBatchGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelInviteBatchGroup) Update() *ChannelInviteBatchGroupUpdateOne {
	return NewChannelInviteBatchGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelInviteBatchGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelInviteBatchGroup) Unwrap() *ChannelInviteBatchGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelInviteBatchGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelInviteBatchGroup) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelInviteBatchGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("batch_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BatchID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelInviteBatchGroups is a parsable slice of ChannelInviteBatchGroup.
type ChannelInviteBatchGroups []*ChannelInviteBatchGroup
