// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChannelInviteBatchDelete is the builder for deleting a ChannelInviteBatch entity.
type ChannelInviteBatchDelete struct {
	config
	hooks    []Hook
	mutation *ChannelInviteBatchMutation
}

// Where appends a list predicates to the ChannelInviteBatchDelete builder.
func (_d *ChannelInviteBatchDelete) Where(ps ...predicate.ChannelInviteBatch) *ChannelInviteBatchDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChannelInviteBatchDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelInviteBatchDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChannelInviteBatchDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(channelinvitebatch.Table, sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChannelInviteBatchDeleteOne is the builder for deleting a single ChannelInviteBatch entity.
type ChannelInviteBatchDeleteOne struct {
	_d *ChannelInviteBatchDelete
}

// Where appends a list predicates to the ChannelInviteBatchDelete builder.
func (_d *ChannelInviteBatchDeleteOne) Where(ps ...predicate.ChannelInviteBatch) *ChannelInviteBatchDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChannelInviteBatchDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{channelinvitebatch.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelInviteBatchDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
