// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ChannelInviteBatch is the model entity for the ChannelInviteBatch schema.
type ChannelInviteBatch struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 批次名称
	Name string `json:"name,omitempty"`
	// 赠送余额金额（U）
	BonusAmount float64 `json:"bonus_amount,omitempty"`
	// 每码最大使用次数，0=无限
	MaxUsesPerCode int `json:"max_uses_per_code,omitempty"`
	// 有效期开始时间
	StartTime *time.Time `json:"start_time,omitempty"`
	// 有效期结束时间
	EndTime *time.Time `json:"end_time,omitempty"`
	// 状态: active, disabled
	Status string `json:"status,omitempty"`
	// 备注
	Notes *string `json:"notes,omitempty"`
	// 创建者用户ID
	CreatedBy int64 `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChannelInviteBatchQuery when eager-loading is set.
	Edges        ChannelInviteBatchEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChannelInviteBatchEdges holds the relations/edges for other nodes in the graph.
type ChannelInviteBatchEdges struct {
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// Codes holds the value of the codes edge.
	Codes []*ChannelInviteCode `json:"codes,omitempty"`
	// BatchGroups holds the value of the batch_groups edge.
	BatchGroups []*ChannelInviteBatchGroup `json:"batch_groups,omitempty"`
	// Usages holds the value of the usages edge.
	Usages []*ChannelInviteCodeUsage `json:"usages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelInviteBatchEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// CodesOrErr returns the Codes value or an error if the edge
// was not loaded in eager-loading.
func (e ChannelInviteBatchEdges) CodesOrErr() ([]*ChannelInviteCode, error) {
	if e.loadedTypes[1] {
		return e.Codes, nil
	}
	return nil, &NotLoadedError{edge: "codes"}
}

// BatchGroupsOrErr returns the BatchGroups value or an error if the edge
// was not loaded in eager-loading.
func (e ChannelInviteBatchEdges) BatchGroupsOrErr() ([]*ChannelInviteBatchGroup, error) {
	if e.loadedTypes[2] {
		return e.BatchGroups, nil
	}
	return nil, &NotLoadedError{edge: "batch_groups"}
}

// UsagesOrErr returns the Usages value or an error if the edge
// was not loaded in eager-loading.
func (e ChannelInviteBatchEdges) UsagesOrErr() ([]*ChannelInviteCodeUsage, error) {
	if e.loadedTypes[3] {
		return e.Usages, nil
	}
	return nil, &NotLoadedError{edge: "usages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelInviteBatch) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelinvitebatch.FieldBonusAmount:
			values[i] = new(sql.NullFloat64)
		case channelinvitebatch.FieldID, channelinvitebatch.FieldMaxUsesPerCode, channelinvitebatch.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case channelinvitebatch.FieldName, channelinvitebatch.FieldStatus, channelinvitebatch.FieldNotes:
			values[i] = new(sql.NullString)
		case channelinvitebatch.FieldStartTime, channelinvitebatch.FieldEndTime, channelinvitebatch.FieldCreatedAt, channelinvitebatch.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelInviteBatch fields.
func (_m *ChannelInviteBatch) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelinvitebatch.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case channelinvitebatch.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case channelinvitebatch.FieldBonusAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_amount", values[i])
			} else if value.Valid {
				_m.BonusAmount = value.Float64
			}
		case channelinvitebatch.FieldMaxUsesPerCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_uses_per_code", values[i])
			} else if value.Valid {
				_m.MaxUsesPerCode = int(value.Int64)
			}
		case channelinvitebatch.FieldStartTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_time", values[i])
			} else if value.Valid {
				_m.StartTime = new(time.Time)
				*_m.StartTime = value.Time
			}
		case channelinvitebatch.FieldEndTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_time", values[i])
			} else if value.Valid {
				_m.EndTime = new(time.Time)
				*_m.EndTime = value.Time
			}
		case channelinvitebatch.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case channelinvitebatch.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case channelinvitebatch.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case channelinvitebatch.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case channelinvitebatch.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelInviteBatch.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelInviteBatch) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCreator queries the "creator" edge of the ChannelInviteBatch entity.
func (_m *ChannelInviteBatch) QueryCreator() *UserQuery {
	return NewChannelInviteBatchClient(_m.config).QueryCreator(_m)
}

// QueryCodes queries the "codes" edge of the ChannelInviteBatch entity.
func (_m *ChannelInviteBatch) QueryCodes() *ChannelInviteCodeQuery {
	return NewChannelInviteBatchClient(_m.config).QueryCodes(_m)
}

// QueryBatchGroups queries the "batch_groups" edge of the ChannelInviteBatch entity.
func (_m *ChannelInviteBatch) QueryBatchGroups() *ChannelInviteBatchGroupQuery {
	return NewChannelInviteBatchClient(_m.config).QueryBatchGroups(_m)
}

// QueryUsages queries the "usages" edge of the ChannelInviteBatch entity.
func (_m *ChannelInviteBatch) QueryUsages() *ChannelInviteCodeUsageQuery {
	return NewChannelInviteBatchClient(_m.config).QueryUsages(_m)
}

// Update returns a builder for updating this ChannelInviteBatch.
// Note that you need to call ChannelInviteBatch.Unwrap() before calling this method if this ChannelInviteBatch
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelInviteBatch) Update() *ChannelInviteBatchUpdateOne {
	return NewChannelInviteBatchClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelInviteBatch entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelInviteBatch) Unwrap() *ChannelInviteBatch {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelInviteBatch is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelInviteBatch) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelInviteBatch(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("bonus_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.BonusAmount))
	builder.WriteString(", ")
	builder.WriteString("max_uses_per_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxUsesPerCode))
	builder.WriteString(", ")
	if v := _m.StartTime; v != nil {
		builder.WriteString("start_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EndTime; v != nil {
		builder.WriteString("end_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelInviteBatches is a parsable slice of ChannelInviteBatch.
type ChannelInviteBatches []*ChannelInviteBatch
