// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatchgroup"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecode"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecodeusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ChannelInviteBatchCreate is the builder for creating a ChannelInviteBatch entity.
type ChannelInviteBatchCreate struct {
	config
	mutation *ChannelInviteBatchMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *ChannelInviteBatchCreate) SetName(v string) *ChannelInviteBatchCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetBonusAmount sets the "bonus_amount" field.
func (_c *ChannelInviteBatchCreate) SetBonusAmount(v float64) *ChannelInviteBatchCreate {
	_c.mutation.SetBonusAmount(v)
	return _c
}

// SetNillableBonusAmount sets the "bonus_amount" field if the given value is not nil.
func (_c *ChannelInviteBatchCreate) SetNillableBonusAmount(v *float64) *ChannelInviteBatchCreate {
	if v != nil {
		_c.SetBonusAmount(*v)
	}
	return _c
}

// SetMaxUsesPerCode sets the "max_uses_per_code" field.
func (_c *ChannelInviteBatchCreate) SetMaxUsesPerCode(v int) *ChannelInviteBatchCreate {
	_c.mutation.SetMaxUsesPerCode(v)
	return _c
}

// SetNillableMaxUsesPerCode sets the "max_uses_per_code" field if the given value is not nil.
func (_c *ChannelInviteBatchCreate) SetNillableMaxUsesPerCode(v *int) *ChannelInviteBatchCreate {
	if v != nil {
		_c.SetMaxUsesPerCode(*v)
	}
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *ChannelInviteBatchCreate) SetStartTime(v time.Time) *ChannelInviteBatchCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_c *ChannelInviteBatchCreate) SetNillableStartTime(v *time.Time) *ChannelInviteBatchCreate {
	if v != nil {
		_c.SetStartTime(*v)
	}
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *ChannelInviteBatchCreate) SetEndTime(v time.Time) *ChannelInviteBatchCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_c *ChannelInviteBatchCreate) SetNillableEndTime(v *time.Time) *ChannelInviteBatchCreate {
	if v != nil {
		_c.SetEndTime(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChannelInviteBatchCreate) SetStatus(v string) *ChannelInviteBatchCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ChannelInviteBatchCreate) SetNillableStatus(v *string) *ChannelInviteBatchCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *ChannelInviteBatchCreate) SetNotes(v string) *ChannelInviteBatchCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *ChannelInviteBatchCreate) SetNillableNotes(v *string) *ChannelInviteBatchCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ChannelInviteBatchCreate) SetCreatedBy(v int64) *ChannelInviteBatchCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelInviteBatchCreate) SetCreatedAt(v time.Time) *ChannelInviteBatchCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelInviteBatchCreate) SetNillableCreatedAt(v *time.Time) *ChannelInviteBatchCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChannelInviteBatchCreate) SetUpdatedAt(v time.Time) *ChannelInviteBatchCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChannelInviteBatchCreate) SetNillableUpdatedAt(v *time.Time) *ChannelInviteBatchCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *ChannelInviteBatchCreate) SetCreatorID(id int64) *ChannelInviteBatchCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *ChannelInviteBatchCreate) SetCreator(v *User) *ChannelInviteBatchCreate {
	return _c.SetCreatorID(v.ID)
}

// AddCodeIDs adds the "codes" edge to the ChannelInviteCode entity by IDs.
func (_c *ChannelInviteBatchCreate) AddCodeIDs(ids ...int64) *ChannelInviteBatchCreate {
	_c.mutation.AddCodeIDs(ids...)
	return _c
}

// AddCodes adds the "codes" edges to the ChannelInviteCode entity.
func (_c *ChannelInviteBatchCreate) AddCodes(v ...*ChannelInviteCode) *ChannelInviteBatchCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCodeIDs(ids...)
}

// AddBatchGroupIDs adds the "batch_groups" edge to the ChannelInviteBatchGroup entity by IDs.
func (_c *ChannelInviteBatchCreate) AddBatchGroupIDs(ids ...int64) *ChannelInviteBatchCreate {
	_c.mutation.AddBatchGroupIDs(ids...)
	return _c
}

// AddBatchGroups adds the "batch_groups" edges to the ChannelInviteBatchGroup entity.
func (_c *ChannelInviteBatchCreate) AddBatchGroups(v ...*ChannelInviteBatchGroup) *ChannelInviteBatchCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBatchGroupIDs(ids...)
}

// AddUsageIDs adds the "usages" edge to the ChannelInviteCodeUsage entity by IDs.
func (_c *ChannelInviteBatchCreate) AddUsageIDs(ids ...int64) *ChannelInviteBatchCreate {
	_c.mutation.AddUsageIDs(ids...)
	return _c
}

// AddUsages adds the "usages" edges to the ChannelInviteCodeUsage entity.
func (_c *ChannelInviteBatchCreate) AddUsages(v ...*ChannelInviteCodeUsage) *ChannelInviteBatchCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageIDs(ids...)
}

// Mutation returns the ChannelInviteBatchMutation object of the builder.
func (_c *ChannelInviteBatchCreate) Mutation() *ChannelInviteBatchMutation {
	return _c.mutation
}

// Save creates the ChannelInviteBatch in the database.
func (_c *ChannelInviteBatchCreate) Save(ctx context.Context) (*ChannelInviteBatch, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelInviteBatchCreate) SaveX(ctx context.Context) *ChannelInviteBatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelInviteBatchCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelInviteBatchCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelInviteBatchCreate) defaults() {
	if _, ok := _c.mutation.BonusAmount(); !ok {
		v := channelinvitebatch.DefaultBonusAmount
		_c.mutation.SetBonusAmount(v)
	}
	if _, ok := _c.mutation.MaxUsesPerCode(); !ok {
		v := channelinvitebatch.DefaultMaxUsesPerCode
		_c.mutation.SetMaxUsesPerCode(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := channelinvitebatch.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := channelinvitebatch.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := channelinvitebatch.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelInviteBatchCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ChannelInviteBatch.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := channelinvitebatch.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChannelInviteBatch.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BonusAmount(); !ok {
		return &ValidationError{Name: "bonus_amount", err: errors.New(`ent: missing required field "ChannelInviteBatch.bonus_amount"`)}
	}
	if _, ok := _c.mutation.MaxUsesPerCode(); !ok {
		return &ValidationError{Name: "max_uses_per_code", err: errors.New(`ent: missing required field "ChannelInviteBatch.max_uses_per_code"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ChannelInviteBatch.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := channelinvitebatch.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChannelInviteBatch.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "ChannelInviteBatch.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChannelInviteBatch.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChannelInviteBatch.updated_at"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "ChannelInviteBatch.creator"`)}
	}
	return nil
}

func (_c *ChannelInviteBatchCreate) sqlSave(ctx context.Context) (*ChannelInviteBatch, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelInviteBatchCreate) createSpec() (*ChannelInviteBatch, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelInviteBatch{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelinvitebatch.Table, sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(channelinvitebatch.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.BonusAmount(); ok {
		_spec.SetField(channelinvitebatch.FieldBonusAmount, field.TypeFloat64, value)
		_node.BonusAmount = value
	}
	if value, ok := _c.mutation.MaxUsesPerCode(); ok {
		_spec.SetField(channelinvitebatch.FieldMaxUsesPerCode, field.TypeInt, value)
		_node.MaxUsesPerCode = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(channelinvitebatch.FieldStartTime, field.TypeTime, value)
		_node.StartTime = &value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(channelinvitebatch.FieldEndTime, field.TypeTime, value)
		_node.EndTime = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(channelinvitebatch.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(channelinvitebatch.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelinvitebatch.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(channelinvitebatch.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatch.CreatorTable,
			Columns: []string{channelinvitebatch.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.CodesTable,
			Columns: []string{channelinvitebatch.CodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BatchGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.BatchGroupsTable,
			Columns: []string{channelinvitebatch.BatchGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatchgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.UsagesTable,
			Columns: []string{channelinvitebatch.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelInviteBatch.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelInviteBatchUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelInviteBatchCreate) OnConflict(opts ...sql.ConflictOption) *ChannelInviteBatchUpsertOne {
	_c.conflict = opts
	return &ChannelInviteBatchUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelInviteBatch.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelInviteBatchCreate) OnConflictColumns(columns ...string) *ChannelInviteBatchUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelInviteBatchUpsertOne{
		create: _c,
	}
}

type (
	// ChannelInviteBatchUpsertOne is the builder for "upsert"-ing
	//  one ChannelInviteBatch node.
	ChannelInviteBatchUpsertOne struct {
		create *ChannelInviteBatchCreate
	}

	// ChannelInviteBatchUpsert is the "OnConflict" setter.
	ChannelInviteBatchUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ChannelInviteBatchUpsert) SetName(v string) *ChannelInviteBatchUpsert {
	u.Set(channelinvitebatch.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsert) UpdateName() *ChannelInviteBatchUpsert {
	u.SetExcluded(channelinvitebatch.FieldName)
	return u
}

// SetBonusAmount sets the "bonus_amount" field.
func (u *ChannelInviteBatchUpsert) SetBonusAmount(v float64) *ChannelInviteBatchUpsert {
	u.Set(channelinvitebatch.FieldBonusAmount, v)
	return u
}

// UpdateBonusAmount sets the "bonus_amount" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsert) UpdateBonusAmount() *ChannelInviteBatchUpsert {
	u.SetExcluded(channelinvitebatch.FieldBonusAmount)
	return u
}

// AddBonusAmount adds v to the "bonus_amount" field.
func (u *ChannelInviteBatchUpsert) AddBonusAmount(v float64) *ChannelInviteBatchUpsert {
	u.Add(channelinvitebatch.FieldBonusAmount, v)
	return u
}

// SetMaxUsesPerCode sets the "max_uses_per_code" field.
func (u *ChannelInviteBatchUpsert) SetMaxUsesPerCode(v int) *ChannelInviteBatchUpsert {
	u.Set(channelinvitebatch.FieldMaxUsesPerCode, v)
	return u
}

// UpdateMaxUsesPerCode sets the "max_uses_per_code" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsert) UpdateMaxUsesPerCode() *ChannelInviteBatchUpsert {
	u.SetExcluded(channelinvitebatch.FieldMaxUsesPerCode)
	return u
}

// AddMaxUsesPerCode adds v to the "max_uses_per_code" field.
func (u *ChannelInviteBatchUpsert) AddMaxUsesPerCode(v int) *ChannelInviteBatchUpsert {
	u.Add(channelinvitebatch.FieldMaxUsesPerCode, v)
	return u
}

// SetStartTime sets the "start_time" field.
func (u *ChannelInviteBatchUpsert) SetStartTime(v time.Time) *ChannelInviteBatchUpsert {
	u.Set(channelinvitebatch.FieldStartTime, v)
	return u
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsert) UpdateStartTime() *ChannelInviteBatchUpsert {
	u.SetExcluded(channelinvitebatch.FieldStartTime)
	return u
}

// ClearStartTime clears the value of the "start_time" field.
func (u *ChannelInviteBatchUpsert) ClearStartTime() *ChannelInviteBatchUpsert {
	u.SetNull(channelinvitebatch.FieldStartTime)
	return u
}

// SetEndTime sets the "end_time" field.
func (u *ChannelInviteBatchUpsert) SetEndTime(v time.Time) *ChannelInviteBatchUpsert {
	u.Set(channelinvitebatch.FieldEndTime, v)
	return u
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsert) UpdateEndTime() *ChannelInviteBatchUpsert {
	u.SetExcluded(channelinvitebatch.FieldEndTime)
	return u
}

// ClearEndTime clears the value of the "end_time" field.
func (u *ChannelInviteBatchUpsert) ClearEndTime() *ChannelInviteBatchUpsert {
	u.SetNull(channelinvitebatch.FieldEndTime)
	return u
}

// SetStatus sets the "status" field.
func (u *ChannelInviteBatchUpsert) SetStatus(v string) *ChannelInviteBatchUpsert {
	u.Set(channelinvitebatch.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsert) UpdateStatus() *ChannelInviteBatchUpsert {
	u.SetExcluded(channelinvitebatch.FieldStatus)
	return u
}

// SetNotes sets the "notes" field.
func (u *ChannelInviteBatchUpsert) SetNotes(v string) *ChannelInviteBatchUpsert {
	u.Set(channelinvitebatch.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsert) UpdateNotes() *ChannelInviteBatchUpsert {
	u.SetExcluded(channelinvitebatch.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *ChannelInviteBatchUpsert) ClearNotes() *ChannelInviteBatchUpsert {
	u.SetNull(channelinvitebatch.FieldNotes)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ChannelInviteBatchUpsert) SetCreatedBy(v int64) *ChannelInviteBatchUpsert {
	u.Set(channelinvitebatch.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsert) UpdateCreatedBy() *ChannelInviteBatchUpsert {
	u.SetExcluded(channelinvitebatch.FieldCreatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelInviteBatchUpsert) SetUpdatedAt(v time.Time) *ChannelInviteBatchUpsert {
	u.Set(channelinvitebatch.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsert) UpdateUpdatedAt() *ChannelInviteBatchUpsert {
	u.SetExcluded(channelinvitebatch.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChannelInviteBatch.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelInviteBatchUpsertOne) UpdateNewValues() *ChannelInviteBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(channelinvitebatch.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelInviteBatch.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelInviteBatchUpsertOne) Ignore() *ChannelInviteBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelInviteBatchUpsertOne) DoNothing() *ChannelInviteBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelInviteBatchCreate.OnConflict
// documentation for more info.
func (u *ChannelInviteBatchUpsertOne) Update(set func(*ChannelInviteBatchUpsert)) *ChannelInviteBatchUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelInviteBatchUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ChannelInviteBatchUpsertOne) SetName(v string) *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertOne) UpdateName() *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateName()
	})
}

// SetBonusAmount sets the "bonus_amount" field.
func (u *ChannelInviteBatchUpsertOne) SetBonusAmount(v float64) *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetBonusAmount(v)
	})
}

// AddBonusAmount adds v to the "bonus_amount" field.
func (u *ChannelInviteBatchUpsertOne) AddBonusAmount(v float64) *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.AddBonusAmount(v)
	})
}

// UpdateBonusAmount sets the "bonus_amount" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertOne) UpdateBonusAmount() *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateBonusAmount()
	})
}

// SetMaxUsesPerCode sets the "max_uses_per_code" field.
func (u *ChannelInviteBatchUpsertOne) SetMaxUsesPerCode(v int) *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetMaxUsesPerCode(v)
	})
}

// AddMaxUsesPerCode adds v to the "max_uses_per_code" field.
func (u *ChannelInviteBatchUpsertOne) AddMaxUsesPerCode(v int) *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.AddMaxUsesPerCode(v)
	})
}

// UpdateMaxUsesPerCode sets the "max_uses_per_code" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertOne) UpdateMaxUsesPerCode() *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateMaxUsesPerCode()
	})
}

// SetStartTime sets the "start_time" field.
func (u *ChannelInviteBatchUpsertOne) SetStartTime(v time.Time) *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertOne) UpdateStartTime() *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateStartTime()
	})
}

// ClearStartTime clears the value of the "start_time" field.
func (u *ChannelInviteBatchUpsertOne) ClearStartTime() *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.ClearStartTime()
	})
}

// SetEndTime sets the "end_time" field.
func (u *ChannelInviteBatchUpsertOne) SetEndTime(v time.Time) *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertOne) UpdateEndTime() *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateEndTime()
	})
}

// ClearEndTime clears the value of the "end_time" field.
func (u *ChannelInviteBatchUpsertOne) ClearEndTime() *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.ClearEndTime()
	})
}

// SetStatus sets the "status" field.
func (u *ChannelInviteBatchUpsertOne) SetStatus(v string) *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertOne) UpdateStatus() *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *ChannelInviteBatchUpsertOne) SetNotes(v string) *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertOne) UpdateNotes() *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ChannelInviteBatchUpsertOne) ClearNotes() *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.ClearNotes()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ChannelInviteBatchUpsertOne) SetCreatedBy(v int64) *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertOne) UpdateCreatedBy() *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelInviteBatchUpsertOne) SetUpdatedAt(v time.Time) *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertOne) UpdateUpdatedAt() *ChannelInviteBatchUpsertOne {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChannelInviteBatchUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelInviteBatchCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelInviteBatchUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelInviteBatchUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelInviteBatchUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelInviteBatchCreateBulk is the builder for creating many ChannelInviteBatch entities in bulk.
type ChannelInviteBatchCreateBulk struct {
	config
	err      error
	builders []*ChannelInviteBatchCreate
	conflict []sql.ConflictOption
}

// Save creates the ChannelInviteBatch entities in the database.
func (_c *ChannelInviteBatchCreateBulk) Save(ctx context.Context) ([]*ChannelInviteBatch, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelInviteBatch, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelInviteBatchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelInviteBatchCreateBulk) SaveX(ctx context.Context) []*ChannelInviteBatch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelInviteBatchCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelInviteBatchCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelInviteBatch.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelInviteBatchUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelInviteBatchCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelInviteBatchUpsertBulk {
	_c.conflict = opts
	return &ChannelInviteBatchUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelInviteBatch.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelInviteBatchCreateBulk) OnConflictColumns(columns ...string) *ChannelInviteBatchUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelInviteBatchUpsertBulk{
		create: _c,
	}
}

// ChannelInviteBatchUpsertBulk is the builder for "upsert"-ing
// a bulk of ChannelInviteBatch nodes.
type ChannelInviteBatchUpsertBulk struct {
	create *ChannelInviteBatchCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChannelInviteBatch.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelInviteBatchUpsertBulk) UpdateNewValues() *ChannelInviteBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(channelinvitebatch.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelInviteBatch.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelInviteBatchUpsertBulk) Ignore() *ChannelInviteBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelInviteBatchUpsertBulk) DoNothing() *ChannelInviteBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelInviteBatchCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelInviteBatchUpsertBulk) Update(set func(*ChannelInviteBatchUpsert)) *ChannelInviteBatchUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelInviteBatchUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ChannelInviteBatchUpsertBulk) SetName(v string) *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertBulk) UpdateName() *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateName()
	})
}

// SetBonusAmount sets the "bonus_amount" field.
func (u *ChannelInviteBatchUpsertBulk) SetBonusAmount(v float64) *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetBonusAmount(v)
	})
}

// AddBonusAmount adds v to the "bonus_amount" field.
func (u *ChannelInviteBatchUpsertBulk) AddBonusAmount(v float64) *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.AddBonusAmount(v)
	})
}

// UpdateBonusAmount sets the "bonus_amount" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertBulk) UpdateBonusAmount() *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateBonusAmount()
	})
}

// SetMaxUsesPerCode sets the "max_uses_per_code" field.
func (u *ChannelInviteBatchUpsertBulk) SetMaxUsesPerCode(v int) *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetMaxUsesPerCode(v)
	})
}

// AddMaxUsesPerCode adds v to the "max_uses_per_code" field.
func (u *ChannelInviteBatchUpsertBulk) AddMaxUsesPerCode(v int) *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.AddMaxUsesPerCode(v)
	})
}

// UpdateMaxUsesPerCode sets the "max_uses_per_code" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertBulk) UpdateMaxUsesPerCode() *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateMaxUsesPerCode()
	})
}

// SetStartTime sets the "start_time" field.
func (u *ChannelInviteBatchUpsertBulk) SetStartTime(v time.Time) *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertBulk) UpdateStartTime() *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateStartTime()
	})
}

// ClearStartTime clears the value of the "start_time" field.
func (u *ChannelInviteBatchUpsertBulk) ClearStartTime() *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.ClearStartTime()
	})
}

// SetEndTime sets the "end_time" field.
func (u *ChannelInviteBatchUpsertBulk) SetEndTime(v time.Time) *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertBulk) UpdateEndTime() *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateEndTime()
	})
}

// ClearEndTime clears the value of the "end_time" field.
func (u *ChannelInviteBatchUpsertBulk) ClearEndTime() *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.ClearEndTime()
	})
}

// SetStatus sets the "status" field.
func (u *ChannelInviteBatchUpsertBulk) SetStatus(v string) *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertBulk) UpdateStatus() *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *ChannelInviteBatchUpsertBulk) SetNotes(v string) *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertBulk) UpdateNotes() *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ChannelInviteBatchUpsertBulk) ClearNotes() *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.ClearNotes()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ChannelInviteBatchUpsertBulk) SetCreatedBy(v int64) *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertBulk) UpdateCreatedBy() *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelInviteBatchUpsertBulk) SetUpdatedAt(v time.Time) *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelInviteBatchUpsertBulk) UpdateUpdatedAt() *ChannelInviteBatchUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ChannelInviteBatchUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelInviteBatchCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelInviteBatchCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelInviteBatchUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
