// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatchgroup"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecode"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecodeusage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ChannelInviteBatchUpdate is the builder for updating ChannelInviteBatch entities.
type ChannelInviteBatchUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelInviteBatchMutation
}

// Where appends a list predicates to the ChannelInviteBatchUpdate builder.
func (_u *ChannelInviteBatchUpdate) Where(ps ...predicate.ChannelInviteBatch) *ChannelInviteBatchUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelInviteBatchUpdate) SetName(v string) *ChannelInviteBatchUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdate) SetNillableName(v *string) *ChannelInviteBatchUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBonusAmount sets the "bonus_amount" field.
func (_u *ChannelInviteBatchUpdate) SetBonusAmount(v float64) *ChannelInviteBatchUpdate {
	_u.mutation.ResetBonusAmount()
	_u.mutation.SetBonusAmount(v)
	return _u
}

// SetNillableBonusAmount sets the "bonus_amount" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdate) SetNillableBonusAmount(v *float64) *ChannelInviteBatchUpdate {
	if v != nil {
		_u.SetBonusAmount(*v)
	}
	return _u
}

// AddBonusAmount adds value to the "bonus_amount" field.
func (_u *ChannelInviteBatchUpdate) AddBonusAmount(v float64) *ChannelInviteBatchUpdate {
	_u.mutation.AddBonusAmount(v)
	return _u
}

// SetMaxUsesPerCode sets the "max_uses_per_code" field.
func (_u *ChannelInviteBatchUpdate) SetMaxUsesPerCode(v int) *ChannelInviteBatchUpdate {
	_u.mutation.ResetMaxUsesPerCode()
	_u.mutation.SetMaxUsesPerCode(v)
	return _u
}

// SetNillableMaxUsesPerCode sets the "max_uses_per_code" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdate) SetNillableMaxUsesPerCode(v *int) *ChannelInviteBatchUpdate {
	if v != nil {
		_u.SetMaxUsesPerCode(*v)
	}
	return _u
}

// AddMaxUsesPerCode adds value to the "max_uses_per_code" field.
func (_u *ChannelInviteBatchUpdate) AddMaxUsesPerCode(v int) *ChannelInviteBatchUpdate {
	_u.mutation.AddMaxUsesPerCode(v)
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *ChannelInviteBatchUpdate) SetStartTime(v time.Time) *ChannelInviteBatchUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdate) SetNillableStartTime(v *time.Time) *ChannelInviteBatchUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// ClearStartTime clears the value of the "start_time" field.
func (_u *ChannelInviteBatchUpdate) ClearStartTime() *ChannelInviteBatchUpdate {
	_u.mutation.ClearStartTime()
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *ChannelInviteBatchUpdate) SetEndTime(v time.Time) *ChannelInviteBatchUpdate {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdate) SetNillableEndTime(v *time.Time) *ChannelInviteBatchUpdate {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *ChannelInviteBatchUpdate) ClearEndTime() *ChannelInviteBatchUpdate {
	_u.mutation.ClearEndTime()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChannelInviteBatchUpdate) SetStatus(v string) *ChannelInviteBatchUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdate) SetNillableStatus(v *string) *ChannelInviteBatchUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ChannelInviteBatchUpdate) SetNotes(v string) *ChannelInviteBatchUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdate) SetNillableNotes(v *string) *ChannelInviteBatchUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ChannelInviteBatchUpdate) ClearNotes() *ChannelInviteBatchUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ChannelInviteBatchUpdate) SetCreatedBy(v int64) *ChannelInviteBatchUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdate) SetNillableCreatedBy(v *int64) *ChannelInviteBatchUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelInviteBatchUpdate) SetUpdatedAt(v time.Time) *ChannelInviteBatchUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *ChannelInviteBatchUpdate) SetCreatorID(id int64) *ChannelInviteBatchUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *ChannelInviteBatchUpdate) SetCreator(v *User) *ChannelInviteBatchUpdate {
	return _u.SetCreatorID(v.ID)
}

// AddCodeIDs adds the "codes" edge to the ChannelInviteCode entity by IDs.
func (_u *ChannelInviteBatchUpdate) AddCodeIDs(ids ...int64) *ChannelInviteBatchUpdate {
	_u.mutation.AddCodeIDs(ids...)
	return _u
}

// AddCodes adds the "codes" edges to the ChannelInviteCode entity.
func (_u *ChannelInviteBatchUpdate) AddCodes(v ...*ChannelInviteCode) *ChannelInviteBatchUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCodeIDs(ids...)
}

// AddBatchGroupIDs adds the "batch_groups" edge to the ChannelInviteBatchGroup entity by IDs.
func (_u *ChannelInviteBatchUpdate) AddBatchGroupIDs(ids ...int64) *ChannelInviteBatchUpdate {
	_u.mutation.AddBatchGroupIDs(ids...)
	return _u
}

// AddBatchGroups adds the "batch_groups" edges to the ChannelInviteBatchGroup entity.
func (_u *ChannelInviteBatchUpdate) AddBatchGroups(v ...*ChannelInviteBatchGroup) *ChannelInviteBatchUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBatchGroupIDs(ids...)
}

// AddUsageIDs adds the "usages" edge to the ChannelInviteCodeUsage entity by IDs.
func (_u *ChannelInviteBatchUpdate) AddUsageIDs(ids ...int64) *ChannelInviteBatchUpdate {
	_u.mutation.AddUsageIDs(ids...)
	return _u
}

// AddUsages adds the "usages" edges to the ChannelInviteCodeUsage entity.
func (_u *ChannelInviteBatchUpdate) AddUsages(v ...*ChannelInviteCodeUsage) *ChannelInviteBatchUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageIDs(ids...)
}

// Mutation returns the ChannelInviteBatchMutation object of the builder.
func (_u *ChannelInviteBatchUpdate) Mutation() *ChannelInviteBatchMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *ChannelInviteBatchUpdate) ClearCreator() *ChannelInviteBatchUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearCodes clears all "codes" edges to the ChannelInviteCode entity.
func (_u *ChannelInviteBatchUpdate) ClearCodes() *ChannelInviteBatchUpdate {
	_u.mutation.ClearCodes()
	return _u
}

// RemoveCodeIDs removes the "codes" edge to ChannelInviteCode entities by IDs.
func (_u *ChannelInviteBatchUpdate) RemoveCodeIDs(ids ...int64) *ChannelInviteBatchUpdate {
	_u.mutation.RemoveCodeIDs(ids...)
	return _u
}

// RemoveCodes removes "codes" edges to ChannelInviteCode entities.
func (_u *ChannelInviteBatchUpdate) RemoveCodes(v ...*ChannelInviteCode) *ChannelInviteBatchUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCodeIDs(ids...)
}

// ClearBatchGroups clears all "batch_groups" edges to the ChannelInviteBatchGroup entity.
func (_u *ChannelInviteBatchUpdate) ClearBatchGroups() *ChannelInviteBatchUpdate {
	_u.mutation.ClearBatchGroups()
	return _u
}

// RemoveBatchGroupIDs removes the "batch_groups" edge to ChannelInviteBatchGroup entities by IDs.
func (_u *ChannelInviteBatchUpdate) RemoveBatchGroupIDs(ids ...int64) *ChannelInviteBatchUpdate {
	_u.mutation.RemoveBatchGroupIDs(ids...)
	return _u
}

// RemoveBatchGroups removes "batch_groups" edges to ChannelInviteBatchGroup entities.
func (_u *ChannelInviteBatchUpdate) RemoveBatchGroups(v ...*ChannelInviteBatchGroup) *ChannelInviteBatchUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBatchGroupIDs(ids...)
}

// ClearUsages clears all "usages" edges to the ChannelInviteCodeUsage entity.
func (_u *ChannelInviteBatchUpdate) ClearUsages() *ChannelInviteBatchUpdate {
	_u.mutation.ClearUsages()
	return _u
}

// RemoveUsageIDs removes the "usages" edge to ChannelInviteCodeUsage entities by IDs.
func (_u *ChannelInviteBatchUpdate) RemoveUsageIDs(ids ...int64) *ChannelInviteBatchUpdate {
	_u.mutation.RemoveUsageIDs(ids...)
	return _u
}

// RemoveUsages removes "usages" edges to ChannelInviteCodeUsage entities.
func (_u *ChannelInviteBatchUpdate) RemoveUsages(v ...*ChannelInviteCodeUsage) *ChannelInviteBatchUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelInviteBatchUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelInviteBatchUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelInviteBatchUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelInviteBatchUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelInviteBatchUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channelinvitebatch.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelInviteBatchUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := channelinvitebatch.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChannelInviteBatch.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := channelinvitebatch.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChannelInviteBatch.status": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteBatch.creator"`)
	}
	return nil
}

func (_u *ChannelInviteBatchUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelinvitebatch.Table, channelinvitebatch.Columns, sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channelinvitebatch.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BonusAmount(); ok {
		_spec.SetField(channelinvitebatch.FieldBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusAmount(); ok {
		_spec.AddField(channelinvitebatch.FieldBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxUsesPerCode(); ok {
		_spec.SetField(channelinvitebatch.FieldMaxUsesPerCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUsesPerCode(); ok {
		_spec.AddField(channelinvitebatch.FieldMaxUsesPerCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(channelinvitebatch.FieldStartTime, field.TypeTime, value)
	}
	if _u.mutation.StartTimeCleared() {
		_spec.ClearField(channelinvitebatch.FieldStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(channelinvitebatch.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(channelinvitebatch.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(channelinvitebatch.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(channelinvitebatch.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(channelinvitebatch.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelinvitebatch.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatch.CreatorTable,
			Columns: []string{channelinvitebatch.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatch.CreatorTable,
			Columns: []string{channelinvitebatch.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.CodesTable,
			Columns: []string{channelinvitebatch.CodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCodesIDs(); len(nodes) > 0 && !_u.mutation.CodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.CodesTable,
			Columns: []string{channelinvitebatch.CodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.CodesTable,
			Columns: []string{channelinvitebatch.CodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BatchGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.BatchGroupsTable,
			Columns: []string{channelinvitebatch.BatchGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatchgroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBatchGroupsIDs(); len(nodes) > 0 && !_u.mutation.BatchGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.BatchGroupsTable,
			Columns: []string{channelinvitebatch.BatchGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatchgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BatchGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.BatchGroupsTable,
			Columns: []string{channelinvitebatch.BatchGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatchgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.UsagesTable,
			Columns: []string{channelinvitebatch.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsagesIDs(); len(nodes) > 0 && !_u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.UsagesTable,
			Columns: []string{channelinvitebatch.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.UsagesTable,
			Columns: []string{channelinvitebatch.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelinvitebatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelInviteBatchUpdateOne is the builder for updating a single ChannelInviteBatch entity.
type ChannelInviteBatchUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelInviteBatchMutation
}

// SetName sets the "name" field.
func (_u *ChannelInviteBatchUpdateOne) SetName(v string) *ChannelInviteBatchUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdateOne) SetNillableName(v *string) *ChannelInviteBatchUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBonusAmount sets the "bonus_amount" field.
func (_u *ChannelInviteBatchUpdateOne) SetBonusAmount(v float64) *ChannelInviteBatchUpdateOne {
	_u.mutation.ResetBonusAmount()
	_u.mutation.SetBonusAmount(v)
	return _u
}

// SetNillableBonusAmount sets the "bonus_amount" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdateOne) SetNillableBonusAmount(v *float64) *ChannelInviteBatchUpdateOne {
	if v != nil {
		_u.SetBonusAmount(*v)
	}
	return _u
}

// AddBonusAmount adds value to the "bonus_amount" field.
func (_u *ChannelInviteBatchUpdateOne) AddBonusAmount(v float64) *ChannelInviteBatchUpdateOne {
	_u.mutation.AddBonusAmount(v)
	return _u
}

// SetMaxUsesPerCode sets the "max_uses_per_code" field.
func (_u *ChannelInviteBatchUpdateOne) SetMaxUsesPerCode(v int) *ChannelInviteBatchUpdateOne {
	_u.mutation.ResetMaxUsesPerCode()
	_u.mutation.SetMaxUsesPerCode(v)
	return _u
}

// SetNillableMaxUsesPerCode sets the "max_uses_per_code" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdateOne) SetNillableMaxUsesPerCode(v *int) *ChannelInviteBatchUpdateOne {
	if v != nil {
		_u.SetMaxUsesPerCode(*v)
	}
	return _u
}

// AddMaxUsesPerCode adds value to the "max_uses_per_code" field.
func (_u *ChannelInviteBatchUpdateOne) AddMaxUsesPerCode(v int) *ChannelInviteBatchUpdateOne {
	_u.mutation.AddMaxUsesPerCode(v)
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *ChannelInviteBatchUpdateOne) SetStartTime(v time.Time) *ChannelInviteBatchUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdateOne) SetNillableStartTime(v *time.Time) *ChannelInviteBatchUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// ClearStartTime clears the value of the "start_time" field.
func (_u *ChannelInviteBatchUpdateOne) ClearStartTime() *ChannelInviteBatchUpdateOne {
	_u.mutation.ClearStartTime()
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *ChannelInviteBatchUpdateOne) SetEndTime(v time.Time) *ChannelInviteBatchUpdateOne {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdateOne) SetNillableEndTime(v *time.Time) *ChannelInviteBatchUpdateOne {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *ChannelInviteBatchUpdateOne) ClearEndTime() *ChannelInviteBatchUpdateOne {
	_u.mutation.ClearEndTime()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChannelInviteBatchUpdateOne) SetStatus(v string) *ChannelInviteBatchUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdateOne) SetNillableStatus(v *string) *ChannelInviteBatchUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ChannelInviteBatchUpdateOne) SetNotes(v string) *ChannelInviteBatchUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdateOne) SetNillableNotes(v *string) *ChannelInviteBatchUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ChannelInviteBatchUpdateOne) ClearNotes() *ChannelInviteBatchUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ChannelInviteBatchUpdateOne) SetCreatedBy(v int64) *ChannelInviteBatchUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ChannelInviteBatchUpdateOne) SetNillableCreatedBy(v *int64) *ChannelInviteBatchUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelInviteBatchUpdateOne) SetUpdatedAt(v time.Time) *ChannelInviteBatchUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *ChannelInviteBatchUpdateOne) SetCreatorID(id int64) *ChannelInviteBatchUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *ChannelInviteBatchUpdateOne) SetCreator(v *User) *ChannelInviteBatchUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// AddCodeIDs adds the "codes" edge to the ChannelInviteCode entity by IDs.
func (_u *ChannelInviteBatchUpdateOne) AddCodeIDs(ids ...int64) *ChannelInviteBatchUpdateOne {
	_u.mutation.AddCodeIDs(ids...)
	return _u
}

// AddCodes adds the "codes" edges to the ChannelInviteCode entity.
func (_u *ChannelInviteBatchUpdateOne) AddCodes(v ...*ChannelInviteCode) *ChannelInviteBatchUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCodeIDs(ids...)
}

// AddBatchGroupIDs adds the "batch_groups" edge to the ChannelInviteBatchGroup entity by IDs.
func (_u *ChannelInviteBatchUpdateOne) AddBatchGroupIDs(ids ...int64) *ChannelInviteBatchUpdateOne {
	_u.mutation.AddBatchGroupIDs(ids...)
	return _u
}

// AddBatchGroups adds the "batch_groups" edges to the ChannelInviteBatchGroup entity.
func (_u *ChannelInviteBatchUpdateOne) AddBatchGroups(v ...*ChannelInviteBatchGroup) *ChannelInviteBatchUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBatchGroupIDs(ids...)
}

// AddUsageIDs adds the "usages" edge to the ChannelInviteCodeUsage entity by IDs.
func (_u *ChannelInviteBatchUpdateOne) AddUsageIDs(ids ...int64) *ChannelInviteBatchUpdateOne {
	_u.mutation.AddUsageIDs(ids...)
	return _u
}

// AddUsages adds the "usages" edges to the ChannelInviteCodeUsage entity.
func (_u *ChannelInviteBatchUpdateOne) AddUsages(v ...*ChannelInviteCodeUsage) *ChannelInviteBatchUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageIDs(ids...)
}

// Mutation returns the ChannelInviteBatchMutation object of the builder.
func (_u *ChannelInviteBatchUpdateOne) Mutation() *ChannelInviteBatchMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *ChannelInviteBatchUpdateOne) ClearCreator() *ChannelInviteBatchUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearCodes clears all "codes" edges to the ChannelInviteCode entity.
func (_u *ChannelInviteBatchUpdateOne) ClearCodes() *ChannelInviteBatchUpdateOne {
	_u.mutation.ClearCodes()
	return _u
}

// RemoveCodeIDs removes the "codes" edge to ChannelInviteCode entities by IDs.
func (_u *ChannelInviteBatchUpdateOne) RemoveCodeIDs(ids ...int64) *ChannelInviteBatchUpdateOne {
	_u.mutation.RemoveCodeIDs(ids...)
	return _u
}

// RemoveCodes removes "codes" edges to ChannelInviteCode entities.
func (_u *ChannelInviteBatchUpdateOne) RemoveCodes(v ...*ChannelInviteCode) *ChannelInviteBatchUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCodeIDs(ids...)
}

// ClearBatchGroups clears all "batch_groups" edges to the ChannelInviteBatchGroup entity.
func (_u *ChannelInviteBatchUpdateOne) ClearBatchGroups() *ChannelInviteBatchUpdateOne {
	_u.mutation.ClearBatchGroups()
	return _u
}

// RemoveBatchGroupIDs removes the "batch_groups" edge to ChannelInviteBatchGroup entities by IDs.
func (_u *ChannelInviteBatchUpdateOne) RemoveBatchGroupIDs(ids ...int64) *ChannelInviteBatchUpdateOne {
	_u.mutation.RemoveBatchGroupIDs(ids...)
	return _u
}

// RemoveBatchGroups removes "batch_groups" edges to ChannelInviteBatchGroup entities.
func (_u *ChannelInviteBatchUpdateOne) RemoveBatchGroups(v ...*ChannelInviteBatchGroup) *ChannelInviteBatchUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBatchGroupIDs(ids...)
}

// ClearUsages clears all "usages" edges to the ChannelInviteCodeUsage entity.
func (_u *ChannelInviteBatchUpdateOne) ClearUsages() *ChannelInviteBatchUpdateOne {
	_u.mutation.ClearUsages()
	return _u
}

// RemoveUsageIDs removes the "usages" edge to ChannelInviteCodeUsage entities by IDs.
func (_u *ChannelInviteBatchUpdateOne) RemoveUsageIDs(ids ...int64) *ChannelInviteBatchUpdateOne {
	_u.mutation.RemoveUsageIDs(ids...)
	return _u
}

// RemoveUsages removes "usages" edges to ChannelInviteCodeUsage entities.
func (_u *ChannelInviteBatchUpdateOne) RemoveUsages(v ...*ChannelInviteCodeUsage) *ChannelInviteBatchUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageIDs(ids...)
}

// Where appends a list predicates to the ChannelInviteBatchUpdate builder.
func (_u *ChannelInviteBatchUpdateOne) Where(ps ...predicate.ChannelInviteBatch) *ChannelInviteBatchUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelInviteBatchUpdateOne) Select(field string, fields ...string) *ChannelInviteBatchUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelInviteBatch entity.
func (_u *ChannelInviteBatchUpdateOne) Save(ctx context.Context) (*ChannelInviteBatch, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelInviteBatchUpdateOne) SaveX(ctx context.Context) *ChannelInviteBatch {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelInviteBatchUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelInviteBatchUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelInviteBatchUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channelinvitebatch.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelInviteBatchUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := channelinvitebatch.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChannelInviteBatch.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := channelinvitebatch.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChannelInviteBatch.status": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteBatch.creator"`)
	}
	return nil
}

func (_u *ChannelInviteBatchUpdateOne) sqlSave(ctx context.Context) (_node *ChannelInviteBatch, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelinvitebatch.Table, channelinvitebatch.Columns, sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelInviteBatch.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelinvitebatch.FieldID)
		for _, f := range fields {
			if !channelinvitebatch.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelinvitebatch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channelinvitebatch.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BonusAmount(); ok {
		_spec.SetField(channelinvitebatch.FieldBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusAmount(); ok {
		_spec.AddField(channelinvitebatch.FieldBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxUsesPerCode(); ok {
		_spec.SetField(channelinvitebatch.FieldMaxUsesPerCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUsesPerCode(); ok {
		_spec.AddField(channelinvitebatch.FieldMaxUsesPerCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(channelinvitebatch.FieldStartTime, field.TypeTime, value)
	}
	if _u.mutation.StartTimeCleared() {
		_spec.ClearField(channelinvitebatch.FieldStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(channelinvitebatch.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(channelinvitebatch.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(channelinvitebatch.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(channelinvitebatch.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(channelinvitebatch.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelinvitebatch.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatch.CreatorTable,
			Columns: []string{channelinvitebatch.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatch.CreatorTable,
			Columns: []string{channelinvitebatch.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.CodesTable,
			Columns: []string{channelinvitebatch.CodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCodesIDs(); len(nodes) > 0 && !_u.mutation.CodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.CodesTable,
			Columns: []string{channelinvitebatch.CodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.CodesTable,
			Columns: []string{channelinvitebatch.CodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BatchGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.BatchGroupsTable,
			Columns: []string{channelinvitebatch.BatchGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatchgroup.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBatchGroupsIDs(); len(nodes) > 0 && !_u.mutation.BatchGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.BatchGroupsTable,
			Columns: []string{channelinvitebatch.BatchGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatchgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BatchGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.BatchGroupsTable,
			Columns: []string{channelinvitebatch.BatchGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatchgroup.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.UsagesTable,
			Columns: []string{channelinvitebatch.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsagesIDs(); len(nodes) > 0 && !_u.mutation.UsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.UsagesTable,
			Columns: []string{channelinvitebatch.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channelinvitebatch.UsagesTable,
			Columns: []string{channelinvitebatch.UsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChannelInviteBatch{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelinvitebatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
