// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatchgroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// ChannelInviteBatchGroupCreate is the builder for creating a ChannelInviteBatchGroup entity.
type ChannelInviteBatchGroupCreate struct {
	config
	mutation *ChannelInviteBatchGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBatchID sets the "batch_id" field.
func (_c *ChannelInviteBatchGroupCreate) SetBatchID(v int64) *ChannelInviteBatchGroupCreate {
	_c.mutation.SetBatchID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ChannelInviteBatchGroupCreate) SetGroupID(v int64) *ChannelInviteBatchGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetBatch sets the "batch" edge to the ChannelInviteBatch entity.
func (_c *ChannelInviteBatchGroupCreate) SetBatch(v *ChannelInviteBatch) *ChannelInviteBatchGroupCreate {
	return _c.SetBatchID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *ChannelInviteBatchGroupCreate) SetGroup(v *Group) *ChannelInviteBatchGroupCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the ChannelInviteBatchGroupMutation object of the builder.
func (_c *ChannelInviteBatchGroupCreate) Mutation() *ChannelInviteBatchGroupMutation {
	return _c.mutation
}

// Save creates the ChannelInviteBatchGroup in the database.
func (_c *ChannelInviteBatchGroupCreate) Save(ctx context.Context) (*ChannelInviteBatchGroup, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelInviteBatchGroupCreate) SaveX(ctx context.Context) *ChannelInviteBatchGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelInviteBatchGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelInviteBatchGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelInviteBatchGroupCreate) check() error {
	if _, ok := _c.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch_id", err: errors.New(`ent: missing required field "ChannelInviteBatchGroup.batch_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "ChannelInviteBatchGroup.group_id"`)}
	}
	if len(_c.mutation.BatchIDs()) == 0 {
		return &ValidationError{Name: "batch", err: errors.New(`ent: missing required edge "ChannelInviteBatchGroup.batch"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "ChannelInviteBatchGroup.group"`)}
	}
	return nil
}

func (_c *ChannelInviteBatchGroupCreate) sqlSave(ctx context.Context) (*ChannelInviteBatchGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelInviteBatchGroupCreate) createSpec() (*ChannelInviteBatchGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelInviteBatchGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelinvitebatchgroup.Table, sqlgraph.NewFieldSpec(channelinvitebatchgroup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if nodes := _c.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatchgroup.BatchTable,
			Columns: []string{channelinvitebatchgroup.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BatchID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitebatchgroup.GroupTable,
			Columns: []string{channelinvitebatchgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelInviteBatchGroup.Create().
//		SetBatchID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelInviteBatchGroupUpsert) {
//			SetBatchID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelInviteBatchGroupCreate) OnConflict(opts ...sql.ConflictOption) *ChannelInviteBatchGroupUpsertOne {
	_c.conflict = opts
	return &ChannelInviteBatchGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelInviteBatchGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelInviteBatchGroupCreate) OnConflictColumns(columns ...string) *ChannelInviteBatchGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelInviteBatchGroupUpsertOne{
		create: _c,
	}
}

type (
	// ChannelInviteBatchGroupUpsertOne is the builder for "upsert"-ing
	//  one ChannelInviteBatchGroup node.
	ChannelInviteBatchGroupUpsertOne struct {
		create *ChannelInviteBatchGroupCreate
	}

	// ChannelInviteBatchGroupUpsert is the "OnConflict" setter.
	ChannelInviteBatchGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetBatchID sets the "batch_id" field.
func (u *ChannelInviteBatchGroupUpsert) SetBatchID(v int64) *ChannelInviteBatchGroupUpsert {
	u.Set(channelinvitebatchgroup.FieldBatchID, v)
	return u
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ChannelInviteBatchGroupUpsert) UpdateBatchID() *ChannelInviteBatchGroupUpsert {
	u.SetExcluded(channelinvitebatchgroup.FieldBatchID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *ChannelInviteBatchGroupUpsert) SetGroupID(v int64) *ChannelInviteBatchGroupUpsert {
	u.Set(channelinvitebatchgroup.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ChannelInviteBatchGroupUpsert) UpdateGroupID() *ChannelInviteBatchGroupUpsert {
	u.SetExcluded(channelinvitebatchgroup.FieldGroupID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChannelInviteBatchGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelInviteBatchGroupUpsertOne) UpdateNewValues() *ChannelInviteBatchGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelInviteBatchGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelInviteBatchGroupUpsertOne) Ignore() *ChannelInviteBatchGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelInviteBatchGroupUpsertOne) DoNothing() *ChannelInviteBatchGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelInviteBatchGroupCreate.OnConflict
// documentation for more info.
func (u *ChannelInviteBatchGroupUpsertOne) Update(set func(*ChannelInviteBatchGroupUpsert)) *ChannelInviteBatchGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelInviteBatchGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *ChannelInviteBatchGroupUpsertOne) SetBatchID(v int64) *ChannelInviteBatchGroupUpsertOne {
	return u.Update(func(s *ChannelInviteBatchGroupUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ChannelInviteBatchGroupUpsertOne) UpdateBatchID() *ChannelInviteBatchGroupUpsertOne {
	return u.Update(func(s *ChannelInviteBatchGroupUpsert) {
		s.UpdateBatchID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ChannelInviteBatchGroupUpsertOne) SetGroupID(v int64) *ChannelInviteBatchGroupUpsertOne {
	return u.Update(func(s *ChannelInviteBatchGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ChannelInviteBatchGroupUpsertOne) UpdateGroupID() *ChannelInviteBatchGroupUpsertOne {
	return u.Update(func(s *ChannelInviteBatchGroupUpsert) {
		s.UpdateGroupID()
	})
}

// Exec executes the query.
func (u *ChannelInviteBatchGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelInviteBatchGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelInviteBatchGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelInviteBatchGroupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelInviteBatchGroupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelInviteBatchGroupCreateBulk is the builder for creating many ChannelInviteBatchGroup entities in bulk.
type ChannelInviteBatchGroupCreateBulk struct {
	config
	err      error
	builders []*ChannelInviteBatchGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the ChannelInviteBatchGroup entities in the database.
func (_c *ChannelInviteBatchGroupCreateBulk) Save(ctx context.Context) ([]*ChannelInviteBatchGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelInviteBatchGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelInviteBatchGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelInviteBatchGroupCreateBulk) SaveX(ctx context.Context) []*ChannelInviteBatchGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelInviteBatchGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelInviteBatchGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelInviteBatchGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelInviteBatchGroupUpsert) {
//			SetBatchID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelInviteBatchGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelInviteBatchGroupUpsertBulk {
	_c.conflict = opts
	return &ChannelInviteBatchGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelInviteBatchGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelInviteBatchGroupCreateBulk) OnConflictColumns(columns ...string) *ChannelInviteBatchGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelInviteBatchGroupUpsertBulk{
		create: _c,
	}
}

// ChannelInviteBatchGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of ChannelInviteBatchGroup nodes.
type ChannelInviteBatchGroupUpsertBulk struct {
	create *ChannelInviteBatchGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChannelInviteBatchGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelInviteBatchGroupUpsertBulk) UpdateNewValues() *ChannelInviteBatchGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelInviteBatchGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelInviteBatchGroupUpsertBulk) Ignore() *ChannelInviteBatchGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelInviteBatchGroupUpsertBulk) DoNothing() *ChannelInviteBatchGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelInviteBatchGroupCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelInviteBatchGroupUpsertBulk) Update(set func(*ChannelInviteBatchGroupUpsert)) *ChannelInviteBatchGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelInviteBatchGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *ChannelInviteBatchGroupUpsertBulk) SetBatchID(v int64) *ChannelInviteBatchGroupUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchGroupUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ChannelInviteBatchGroupUpsertBulk) UpdateBatchID() *ChannelInviteBatchGroupUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchGroupUpsert) {
		s.UpdateBatchID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ChannelInviteBatchGroupUpsertBulk) SetGroupID(v int64) *ChannelInviteBatchGroupUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ChannelInviteBatchGroupUpsertBulk) UpdateGroupID() *ChannelInviteBatchGroupUpsertBulk {
	return u.Update(func(s *ChannelInviteBatchGroupUpsert) {
		s.UpdateGroupID()
	})
}

// Exec executes the query.
func (u *ChannelInviteBatchGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelInviteBatchGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelInviteBatchGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelInviteBatchGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
