// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecode"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecodeusage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ChannelInviteCodeUsageUpdate is the builder for updating ChannelInviteCodeUsage entities.
type ChannelInviteCodeUsageUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelInviteCodeUsageMutation
}

// Where appends a list predicates to the ChannelInviteCodeUsageUpdate builder.
func (_u *ChannelInviteCodeUsageUpdate) Where(ps ...predicate.ChannelInviteCodeUsage) *ChannelInviteCodeUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCodeID sets the "code_id" field.
func (_u *ChannelInviteCodeUsageUpdate) SetCodeID(v int64) *ChannelInviteCodeUsageUpdate {
	_u.mutation.SetCodeID(v)
	return _u
}

// SetNillableCodeID sets the "code_id" field if the given value is not nil.
func (_u *ChannelInviteCodeUsageUpdate) SetNillableCodeID(v *int64) *ChannelInviteCodeUsageUpdate {
	if v != nil {
		_u.SetCodeID(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *ChannelInviteCodeUsageUpdate) SetBatchID(v int64) *ChannelInviteCodeUsageUpdate {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *ChannelInviteCodeUsageUpdate) SetNillableBatchID(v *int64) *ChannelInviteCodeUsageUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChannelInviteCodeUsageUpdate) SetUserID(v int64) *ChannelInviteCodeUsageUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChannelInviteCodeUsageUpdate) SetNillableUserID(v *int64) *ChannelInviteCodeUsageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBonusGranted sets the "bonus_granted" field.
func (_u *ChannelInviteCodeUsageUpdate) SetBonusGranted(v bool) *ChannelInviteCodeUsageUpdate {
	_u.mutation.SetBonusGranted(v)
	return _u
}

// SetNillableBonusGranted sets the "bonus_granted" field if the given value is not nil.
func (_u *ChannelInviteCodeUsageUpdate) SetNillableBonusGranted(v *bool) *ChannelInviteCodeUsageUpdate {
	if v != nil {
		_u.SetBonusGranted(*v)
	}
	return _u
}

// SetBonusGrantedAt sets the "bonus_granted_at" field.
func (_u *ChannelInviteCodeUsageUpdate) SetBonusGrantedAt(v time.Time) *ChannelInviteCodeUsageUpdate {
	_u.mutation.SetBonusGrantedAt(v)
	return _u
}

// SetNillableBonusGrantedAt sets the "bonus_granted_at" field if the given value is not nil.
func (_u *ChannelInviteCodeUsageUpdate) SetNillableBonusGrantedAt(v *time.Time) *ChannelInviteCodeUsageUpdate {
	if v != nil {
		_u.SetBonusGrantedAt(*v)
	}
	return _u
}

// ClearBonusGrantedAt clears the value of the "bonus_granted_at" field.
func (_u *ChannelInviteCodeUsageUpdate) ClearBonusGrantedAt() *ChannelInviteCodeUsageUpdate {
	_u.mutation.ClearBonusGrantedAt()
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *ChannelInviteCodeUsageUpdate) SetClaimedAt(v time.Time) *ChannelInviteCodeUsageUpdate {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *ChannelInviteCodeUsageUpdate) SetNillableClaimedAt(v *time.Time) *ChannelInviteCodeUsageUpdate {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// SetCode sets the "code" edge to the ChannelInviteCode entity.
func (_u *ChannelInviteCodeUsageUpdate) SetCode(v *ChannelInviteCode) *ChannelInviteCodeUsageUpdate {
	return _u.SetCodeID(v.ID)
}

// SetBatch sets the "batch" edge to the ChannelInviteBatch entity.
func (_u *ChannelInviteCodeUsageUpdate) SetBatch(v *ChannelInviteBatch) *ChannelInviteCodeUsageUpdate {
	return _u.SetBatchID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChannelInviteCodeUsageUpdate) SetUser(v *User) *ChannelInviteCodeUsageUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ChannelInviteCodeUsageMutation object of the builder.
func (_u *ChannelInviteCodeUsageUpdate) Mutation() *ChannelInviteCodeUsageMutation {
	return _u.mutation
}

// ClearCode clears the "code" edge to the ChannelInviteCode entity.
func (_u *ChannelInviteCodeUsageUpdate) ClearCode() *ChannelInviteCodeUsageUpdate {
	_u.mutation.ClearCode()
	return _u
}

// ClearBatch clears the "batch" edge to the ChannelInviteBatch entity.
func (_u *ChannelInviteCodeUsageUpdate) ClearBatch() *ChannelInviteCodeUsageUpdate {
	_u.mutation.ClearBatch()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChannelInviteCodeUsageUpdate) ClearUser() *ChannelInviteCodeUsageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelInviteCodeUsageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelInviteCodeUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelInviteCodeUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelInviteCodeUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelInviteCodeUsageUpdate) check() error {
	if _u.mutation.CodeCleared() && len(_u.mutation.CodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteCodeUsage.code"`)
	}
	if _u.mutation.BatchCleared() && len(_u.mutation.BatchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteCodeUsage.batch"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteCodeUsage.user"`)
	}
	return nil
}

func (_u *ChannelInviteCodeUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelinvitecodeusage.Table, channelinvitecodeusage.Columns, sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BonusGranted(); ok {
		_spec.SetField(channelinvitecodeusage.FieldBonusGranted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BonusGrantedAt(); ok {
		_spec.SetField(channelinvitecodeusage.FieldBonusGrantedAt, field.TypeTime, value)
	}
	if _u.mutation.BonusGrantedAtCleared() {
		_spec.ClearField(channelinvitecodeusage.FieldBonusGrantedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(channelinvitecodeusage.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.CodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.CodeTable,
			Columns: []string{channelinvitecodeusage.CodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.CodeTable,
			Columns: []string{channelinvitecodeusage.CodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.BatchTable,
			Columns: []string{channelinvitecodeusage.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.BatchTable,
			Columns: []string{channelinvitecodeusage.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.UserTable,
			Columns: []string{channelinvitecodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.UserTable,
			Columns: []string{channelinvitecodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelinvitecodeusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelInviteCodeUsageUpdateOne is the builder for updating a single ChannelInviteCodeUsage entity.
type ChannelInviteCodeUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelInviteCodeUsageMutation
}

// SetCodeID sets the "code_id" field.
func (_u *ChannelInviteCodeUsageUpdateOne) SetCodeID(v int64) *ChannelInviteCodeUsageUpdateOne {
	_u.mutation.SetCodeID(v)
	return _u
}

// SetNillableCodeID sets the "code_id" field if the given value is not nil.
func (_u *ChannelInviteCodeUsageUpdateOne) SetNillableCodeID(v *int64) *ChannelInviteCodeUsageUpdateOne {
	if v != nil {
		_u.SetCodeID(*v)
	}
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *ChannelInviteCodeUsageUpdateOne) SetBatchID(v int64) *ChannelInviteCodeUsageUpdateOne {
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *ChannelInviteCodeUsageUpdateOne) SetNillableBatchID(v *int64) *ChannelInviteCodeUsageUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChannelInviteCodeUsageUpdateOne) SetUserID(v int64) *ChannelInviteCodeUsageUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChannelInviteCodeUsageUpdateOne) SetNillableUserID(v *int64) *ChannelInviteCodeUsageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBonusGranted sets the "bonus_granted" field.
func (_u *ChannelInviteCodeUsageUpdateOne) SetBonusGranted(v bool) *ChannelInviteCodeUsageUpdateOne {
	_u.mutation.SetBonusGranted(v)
	return _u
}

// SetNillableBonusGranted sets the "bonus_granted" field if the given value is not nil.
func (_u *ChannelInviteCodeUsageUpdateOne) SetNillableBonusGranted(v *bool) *ChannelInviteCodeUsageUpdateOne {
	if v != nil {
		_u.SetBonusGranted(*v)
	}
	return _u
}

// SetBonusGrantedAt sets the "bonus_granted_at" field.
func (_u *ChannelInviteCodeUsageUpdateOne) SetBonusGrantedAt(v time.Time) *ChannelInviteCodeUsageUpdateOne {
	_u.mutation.SetBonusGrantedAt(v)
	return _u
}

// SetNillableBonusGrantedAt sets the "bonus_granted_at" field if the given value is not nil.
func (_u *ChannelInviteCodeUsageUpdateOne) SetNillableBonusGrantedAt(v *time.Time) *ChannelInviteCodeUsageUpdateOne {
	if v != nil {
		_u.SetBonusGrantedAt(*v)
	}
	return _u
}

// ClearBonusGrantedAt clears the value of the "bonus_granted_at" field.
func (_u *ChannelInviteCodeUsageUpdateOne) ClearBonusGrantedAt() *ChannelInviteCodeUsageUpdateOne {
	_u.mutation.ClearBonusGrantedAt()
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *ChannelInviteCodeUsageUpdateOne) SetClaimedAt(v time.Time) *ChannelInviteCodeUsageUpdateOne {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *ChannelInviteCodeUsageUpdateOne) SetNillableClaimedAt(v *time.Time) *ChannelInviteCodeUsageUpdateOne {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// SetCode sets the "code" edge to the ChannelInviteCode entity.
func (_u *ChannelInviteCodeUsageUpdateOne) SetCode(v *ChannelInviteCode) *ChannelInviteCodeUsageUpdateOne {
	return _u.SetCodeID(v.ID)
}

// SetBatch sets the "batch" edge to the ChannelInviteBatch entity.
func (_u *ChannelInviteCodeUsageUpdateOne) SetBatch(v *ChannelInviteBatch) *ChannelInviteCodeUsageUpdateOne {
	return _u.SetBatchID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChannelInviteCodeUsageUpdateOne) SetUser(v *User) *ChannelInviteCodeUsageUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ChannelInviteCodeUsageMutation object of the builder.
func (_u *ChannelInviteCodeUsageUpdateOne) Mutation() *ChannelInviteCodeUsageMutation {
	return _u.mutation
}

// ClearCode clears the "code" edge to the ChannelInviteCode entity.
func (_u *ChannelInviteCodeUsageUpdateOne) ClearCode() *ChannelInviteCodeUsageUpdateOne {
	_u.mutation.ClearCode()
	return _u
}

// ClearBatch clears the "batch" edge to the ChannelInviteBatch entity.
func (_u *ChannelInviteCodeUsageUpdateOne) ClearBatch() *ChannelInviteCodeUsageUpdateOne {
	_u.mutation.ClearBatch()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChannelInviteCodeUsageUpdateOne) ClearUser() *ChannelInviteCodeUsageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ChannelInviteCodeUsageUpdate builder.
func (_u *ChannelInviteCodeUsageUpdateOne) Where(ps ...predicate.ChannelInviteCodeUsage) *ChannelInviteCodeUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelInviteCodeUsageUpdateOne) Select(field string, fields ...string) *ChannelInviteCodeUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelInviteCodeUsage entity.
func (_u *ChannelInviteCodeUsageUpdateOne) Save(ctx context.Context) (*ChannelInviteCodeUsage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelInviteCodeUsageUpdateOne) SaveX(ctx context.Context) *ChannelInviteCodeUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelInviteCodeUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelInviteCodeUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelInviteCodeUsageUpdateOne) check() error {
	if _u.mutation.CodeCleared() && len(_u.mutation.CodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteCodeUsage.code"`)
	}
	if _u.mutation.BatchCleared() && len(_u.mutation.BatchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteCodeUsage.batch"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelInviteCodeUsage.user"`)
	}
	return nil
}

func (_u *ChannelInviteCodeUsageUpdateOne) sqlSave(ctx context.Context) (_node *ChannelInviteCodeUsage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelinvitecodeusage.Table, channelinvitecodeusage.Columns, sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelInviteCodeUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelinvitecodeusage.FieldID)
		for _, f := range fields {
			if !channelinvitecodeusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelinvitecodeusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BonusGranted(); ok {
		_spec.SetField(channelinvitecodeusage.FieldBonusGranted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BonusGrantedAt(); ok {
		_spec.SetField(channelinvitecodeusage.FieldBonusGrantedAt, field.TypeTime, value)
	}
	if _u.mutation.BonusGrantedAtCleared() {
		_spec.ClearField(channelinvitecodeusage.FieldBonusGrantedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(channelinvitecodeusage.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.CodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.CodeTable,
			Columns: []string{channelinvitecodeusage.CodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.CodeTable,
			Columns: []string{channelinvitecodeusage.CodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.BatchTable,
			Columns: []string{channelinvitecodeusage.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.BatchTable,
			Columns: []string{channelinvitecodeusage.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.UserTable,
			Columns: []string{channelinvitecodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.UserTable,
			Columns: []string{channelinvitecodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChannelInviteCodeUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelinvitecodeusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
