// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecode"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecodeusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ChannelInviteCodeUsage is the model entity for the ChannelInviteCodeUsage schema.
type ChannelInviteCodeUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 邀请码ID
	CodeID int64 `json:"code_id,omitempty"`
	// 批次ID
	BatchID int64 `json:"batch_id,omitempty"`
	// 兑换用户ID
	UserID int64 `json:"user_id,omitempty"`
	// 奖励是否已发放
	BonusGranted bool `json:"bonus_granted,omitempty"`
	// 奖励发放时间
	BonusGrantedAt *time.Time `json:"bonus_granted_at,omitempty"`
	// 兑换时间
	ClaimedAt time.Time `json:"claimed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChannelInviteCodeUsageQuery when eager-loading is set.
	Edges        ChannelInviteCodeUsageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChannelInviteCodeUsageEdges holds the relations/edges for other nodes in the graph.
type ChannelInviteCodeUsageEdges struct {
	// Code holds the value of the code edge.
	Code *ChannelInviteCode `json:"code,omitempty"`
	// Batch holds the value of the batch edge.
	Batch *ChannelInviteBatch `json:"batch,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CodeOrErr returns the Code value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelInviteCodeUsageEdges) CodeOrErr() (*ChannelInviteCode, error) {
	if e.Code != nil {
		return e.Code, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channelinvitecode.Label}
	}
	return nil, &NotLoadedError{edge: "code"}
}

// BatchOrErr returns the Batch value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelInviteCodeUsageEdges) BatchOrErr() (*ChannelInviteBatch, error) {
	if e.Batch != nil {
		return e.Batch, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: channelinvitebatch.Label}
	}
	return nil, &NotLoadedError{edge: "batch"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelInviteCodeUsageEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelInviteCodeUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelinvitecodeusage.FieldBonusGranted:
			values[i] = new(sql.NullBool)
		case channelinvitecodeusage.FieldID, channelinvitecodeusage.FieldCodeID, channelinvitecodeusage.FieldBatchID, channelinvitecodeusage.FieldUserID:
			values[i] = new(sql.NullInt64)
		case channelinvitecodeusage.FieldBonusGrantedAt, channelinvitecodeusage.FieldClaimedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelInviteCodeUsage fields.
func (_m *ChannelInviteCodeUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelinvitecodeusage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case channelinvitecodeusage.FieldCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field code_id", values[i])
			} else if value.Valid {
				_m.CodeID = value.Int64
			}
		case channelinvitecodeusage.FieldBatchID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field batch_id", values[i])
			} else if value.Valid {
				_m.BatchID = value.Int64
			}
		case channelinvitecodeusage.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case channelinvitecodeusage.FieldBonusGranted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_granted", values[i])
			} else if value.Valid {
				_m.BonusGranted = value.Bool
			}
		case channelinvitecodeusage.FieldBonusGrantedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_granted_at", values[i])
			} else if value.Valid {
				_m.BonusGrantedAt = new(time.Time)
				*_m.BonusGrantedAt = value.Time
			}
		case channelinvitecodeusage.FieldClaimedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field claimed_at", values[i])
			} else if value.Valid {
				_m.ClaimedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelInviteCodeUsage.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelInviteCodeUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCode queries the "code" edge of the ChannelInviteCodeUsage entity.
func (_m *ChannelInviteCodeUsage) QueryCode() *ChannelInviteCodeQuery {
	return NewChannelInviteCodeUsageClient(_m.config).QueryCode(_m)
}

// QueryBatch queries the "batch" edge of the ChannelInviteCodeUsage entity.
func (_m *ChannelInviteCodeUsage) QueryBatch() *ChannelInviteBatchQuery {
	return NewChannelInviteCodeUsageClient(_m.config).QueryBatch(_m)
}

// QueryUser queries the "user" edge of the ChannelInviteCodeUsage entity.
func (_m *ChannelInviteCodeUsage) QueryUser() *UserQuery {
	return NewChannelInviteCodeUsageClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ChannelInviteCodeUsage.
// Note that you need to call ChannelInviteCodeUsage.Unwrap() before calling this method if this ChannelInviteCodeUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelInviteCodeUsage) Update() *ChannelInviteCodeUsageUpdateOne {
	return NewChannelInviteCodeUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelInviteCodeUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelInviteCodeUsage) Unwrap() *ChannelInviteCodeUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelInviteCodeUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelInviteCodeUsage) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelInviteCodeUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CodeID))
	builder.WriteString(", ")
	builder.WriteString("batch_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BatchID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("bonus_granted=")
	builder.WriteString(fmt.Sprintf("%v", _m.BonusGranted))
	builder.WriteString(", ")
	if v := _m.BonusGrantedAt; v != nil {
		builder.WriteString("bonus_granted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("claimed_at=")
	builder.WriteString(_m.ClaimedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelInviteCodeUsages is a parsable slice of ChannelInviteCodeUsage.
type ChannelInviteCodeUsages []*ChannelInviteCodeUsage
