// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitebatch"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecode"
	"github.com/Wei-Shaw/sub2api/ent/channelinvitecodeusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ChannelInviteCodeUsageCreate is the builder for creating a ChannelInviteCodeUsage entity.
type ChannelInviteCodeUsageCreate struct {
	config
	mutation *ChannelInviteCodeUsageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCodeID sets the "code_id" field.
func (_c *ChannelInviteCodeUsageCreate) SetCodeID(v int64) *ChannelInviteCodeUsageCreate {
	_c.mutation.SetCodeID(v)
	return _c
}

// SetBatchID sets the "batch_id" field.
func (_c *ChannelInviteCodeUsageCreate) SetBatchID(v int64) *ChannelInviteCodeUsageCreate {
	_c.mutation.SetBatchID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChannelInviteCodeUsageCreate) SetUserID(v int64) *ChannelInviteCodeUsageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetBonusGranted sets the "bonus_granted" field.
func (_c *ChannelInviteCodeUsageCreate) SetBonusGranted(v bool) *ChannelInviteCodeUsageCreate {
	_c.mutation.SetBonusGranted(v)
	return _c
}

// SetNillableBonusGranted sets the "bonus_granted" field if the given value is not nil.
func (_c *ChannelInviteCodeUsageCreate) SetNillableBonusGranted(v *bool) *ChannelInviteCodeUsageCreate {
	if v != nil {
		_c.SetBonusGranted(*v)
	}
	return _c
}

// SetBonusGrantedAt sets the "bonus_granted_at" field.
func (_c *ChannelInviteCodeUsageCreate) SetBonusGrantedAt(v time.Time) *ChannelInviteCodeUsageCreate {
	_c.mutation.SetBonusGrantedAt(v)
	return _c
}

// SetNillableBonusGrantedAt sets the "bonus_granted_at" field if the given value is not nil.
func (_c *ChannelInviteCodeUsageCreate) SetNillableBonusGrantedAt(v *time.Time) *ChannelInviteCodeUsageCreate {
	if v != nil {
		_c.SetBonusGrantedAt(*v)
	}
	return _c
}

// SetClaimedAt sets the "claimed_at" field.
func (_c *ChannelInviteCodeUsageCreate) SetClaimedAt(v time.Time) *ChannelInviteCodeUsageCreate {
	_c.mutation.SetClaimedAt(v)
	return _c
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_c *ChannelInviteCodeUsageCreate) SetNillableClaimedAt(v *time.Time) *ChannelInviteCodeUsageCreate {
	if v != nil {
		_c.SetClaimedAt(*v)
	}
	return _c
}

// SetCode sets the "code" edge to the ChannelInviteCode entity.
func (_c *ChannelInviteCodeUsageCreate) SetCode(v *ChannelInviteCode) *ChannelInviteCodeUsageCreate {
	return _c.SetCodeID(v.ID)
}

// SetBatch sets the "batch" edge to the ChannelInviteBatch entity.
func (_c *ChannelInviteCodeUsageCreate) SetBatch(v *ChannelInviteBatch) *ChannelInviteCodeUsageCreate {
	return _c.SetBatchID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChannelInviteCodeUsageCreate) SetUser(v *User) *ChannelInviteCodeUsageCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ChannelInviteCodeUsageMutation object of the builder.
func (_c *ChannelInviteCodeUsageCreate) Mutation() *ChannelInviteCodeUsageMutation {
	return _c.mutation
}

// Save creates the ChannelInviteCodeUsage in the database.
func (_c *ChannelInviteCodeUsageCreate) Save(ctx context.Context) (*ChannelInviteCodeUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelInviteCodeUsageCreate) SaveX(ctx context.Context) *ChannelInviteCodeUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelInviteCodeUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelInviteCodeUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelInviteCodeUsageCreate) defaults() {
	if _, ok := _c.mutation.BonusGranted(); !ok {
		v := channelinvitecodeusage.DefaultBonusGranted
		_c.mutation.SetBonusGranted(v)
	}
	if _, ok := _c.mutation.ClaimedAt(); !ok {
		v := channelinvitecodeusage.DefaultClaimedAt()
		_c.mutation.SetClaimedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelInviteCodeUsageCreate) check() error {
	if _, ok := _c.mutation.CodeID(); !ok {
		return &ValidationError{Name: "code_id", err: errors.New(`ent: missing required field "ChannelInviteCodeUsage.code_id"`)}
	}
	if _, ok := _c.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch_id", err: errors.New(`ent: missing required field "ChannelInviteCodeUsage.batch_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ChannelInviteCodeUsage.user_id"`)}
	}
	if _, ok := _c.mutation.BonusGranted(); !ok {
		return &ValidationError{Name: "bonus_granted", err: errors.New(`ent: missing required field "ChannelInviteCodeUsage.bonus_granted"`)}
	}
	if _, ok := _c.mutation.ClaimedAt(); !ok {
		return &ValidationError{Name: "claimed_at", err: errors.New(`ent: missing required field "ChannelInviteCodeUsage.claimed_at"`)}
	}
	if len(_c.mutation.CodeIDs()) == 0 {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required edge "ChannelInviteCodeUsage.code"`)}
	}
	if len(_c.mutation.BatchIDs()) == 0 {
		return &ValidationError{Name: "batch", err: errors.New(`ent: missing required edge "ChannelInviteCodeUsage.batch"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ChannelInviteCodeUsage.user"`)}
	}
	return nil
}

func (_c *ChannelInviteCodeUsageCreate) sqlSave(ctx context.Context) (*ChannelInviteCodeUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelInviteCodeUsageCreate) createSpec() (*ChannelInviteCodeUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelInviteCodeUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelinvitecodeusage.Table, sqlgraph.NewFieldSpec(channelinvitecodeusage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.BonusGranted(); ok {
		_spec.SetField(channelinvitecodeusage.FieldBonusGranted, field.TypeBool, value)
		_node.BonusGranted = value
	}
	if value, ok := _c.mutation.BonusGrantedAt(); ok {
		_spec.SetField(channelinvitecodeusage.FieldBonusGrantedAt, field.TypeTime, value)
		_node.BonusGrantedAt = &value
	}
	if value, ok := _c.mutation.ClaimedAt(); ok {
		_spec.SetField(channelinvitecodeusage.FieldClaimedAt, field.TypeTime, value)
		_node.ClaimedAt = value
	}
	if nodes := _c.mutation.CodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.CodeTable,
			Columns: []string{channelinvitecodeusage.CodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitecode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.BatchTable,
			Columns: []string{channelinvitecodeusage.BatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelinvitebatch.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BatchID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelinvitecodeusage.UserTable,
			Columns: []string{channelinvitecodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelInviteCodeUsage.Create().
//		SetCodeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelInviteCodeUsageUpsert) {
//			SetCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelInviteCodeUsageCreate) OnConflict(opts ...sql.ConflictOption) *ChannelInviteCodeUsageUpsertOne {
	_c.conflict = opts
	return &ChannelInviteCodeUsageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelInviteCodeUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelInviteCodeUsageCreate) OnConflictColumns(columns ...string) *ChannelInviteCodeUsageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelInviteCodeUsageUpsertOne{
		create: _c,
	}
}

type (
	// ChannelInviteCodeUsageUpsertOne is the builder for "upsert"-ing
	//  one ChannelInviteCodeUsage node.
	ChannelInviteCodeUsageUpsertOne struct {
		create *ChannelInviteCodeUsageCreate
	}

	// ChannelInviteCodeUsageUpsert is the "OnConflict" setter.
	ChannelInviteCodeUsageUpsert struct {
		*sql.UpdateSet
	}
)

// SetCodeID sets the "code_id" field.
func (u *ChannelInviteCodeUsageUpsert) SetCodeID(v int64) *ChannelInviteCodeUsageUpsert {
	u.Set(channelinvitecodeusage.FieldCodeID, v)
	return u
}

// UpdateCodeID sets the "code_id" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsert) UpdateCodeID() *ChannelInviteCodeUsageUpsert {
	u.SetExcluded(channelinvitecodeusage.FieldCodeID)
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *ChannelInviteCodeUsageUpsert) SetBatchID(v int64) *ChannelInviteCodeUsageUpsert {
	u.Set(channelinvitecodeusage.FieldBatchID, v)
	return u
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsert) UpdateBatchID() *ChannelInviteCodeUsageUpsert {
	u.SetExcluded(channelinvitecodeusage.FieldBatchID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ChannelInviteCodeUsageUpsert) SetUserID(v int64) *ChannelInviteCodeUsageUpsert {
	u.Set(channelinvitecodeusage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsert) UpdateUserID() *ChannelInviteCodeUsageUpsert {
	u.SetExcluded(channelinvitecodeusage.FieldUserID)
	return u
}

// SetBonusGranted sets the "bonus_granted" field.
func (u *ChannelInviteCodeUsageUpsert) SetBonusGranted(v bool) *ChannelInviteCodeUsageUpsert {
	u.Set(channelinvitecodeusage.FieldBonusGranted, v)
	return u
}

// UpdateBonusGranted sets the "bonus_granted" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsert) UpdateBonusGranted() *ChannelInviteCodeUsageUpsert {
	u.SetExcluded(channelinvitecodeusage.FieldBonusGranted)
	return u
}

// SetBonusGrantedAt sets the "bonus_granted_at" field.
func (u *ChannelInviteCodeUsageUpsert) SetBonusGrantedAt(v time.Time) *ChannelInviteCodeUsageUpsert {
	u.Set(channelinvitecodeusage.FieldBonusGrantedAt, v)
	return u
}

// UpdateBonusGrantedAt sets the "bonus_granted_at" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsert) UpdateBonusGrantedAt() *ChannelInviteCodeUsageUpsert {
	u.SetExcluded(channelinvitecodeusage.FieldBonusGrantedAt)
	return u
}

// ClearBonusGrantedAt clears the value of the "bonus_granted_at" field.
func (u *ChannelInviteCodeUsageUpsert) ClearBonusGrantedAt() *ChannelInviteCodeUsageUpsert {
	u.SetNull(channelinvitecodeusage.FieldBonusGrantedAt)
	return u
}

// SetClaimedAt sets the "claimed_at" field.
func (u *ChannelInviteCodeUsageUpsert) SetClaimedAt(v time.Time) *ChannelInviteCodeUsageUpsert {
	u.Set(channelinvitecodeusage.FieldClaimedAt, v)
	return u
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsert) UpdateClaimedAt() *ChannelInviteCodeUsageUpsert {
	u.SetExcluded(channelinvitecodeusage.FieldClaimedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChannelInviteCodeUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelInviteCodeUsageUpsertOne) UpdateNewValues() *ChannelInviteCodeUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelInviteCodeUsage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelInviteCodeUsageUpsertOne) Ignore() *ChannelInviteCodeUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelInviteCodeUsageUpsertOne) DoNothing() *ChannelInviteCodeUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelInviteCodeUsageCreate.OnConflict
// documentation for more info.
func (u *ChannelInviteCodeUsageUpsertOne) Update(set func(*ChannelInviteCodeUsageUpsert)) *ChannelInviteCodeUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelInviteCodeUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetCodeID sets the "code_id" field.
func (u *ChannelInviteCodeUsageUpsertOne) SetCodeID(v int64) *ChannelInviteCodeUsageUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.SetCodeID(v)
	})
}

// UpdateCodeID sets the "code_id" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsertOne) UpdateCodeID() *ChannelInviteCodeUsageUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.UpdateCodeID()
	})
}

// SetBatchID sets the "batch_id" field.
func (u *ChannelInviteCodeUsageUpsertOne) SetBatchID(v int64) *ChannelInviteCodeUsageUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsertOne) UpdateBatchID() *ChannelInviteCodeUsageUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.UpdateBatchID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ChannelInviteCodeUsageUpsertOne) SetUserID(v int64) *ChannelInviteCodeUsageUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsertOne) UpdateUserID() *ChannelInviteCodeUsageUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetBonusGranted sets the "bonus_granted" field.
func (u *ChannelInviteCodeUsageUpsertOne) SetBonusGranted(v bool) *ChannelInviteCodeUsageUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.SetBonusGranted(v)
	})
}

// UpdateBonusGranted sets the "bonus_granted" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsertOne) UpdateBonusGranted() *ChannelInviteCodeUsageUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.UpdateBonusGranted()
	})
}

// SetBonusGrantedAt sets the "bonus_granted_at" field.
func (u *ChannelInviteCodeUsageUpsertOne) SetBonusGrantedAt(v time.Time) *ChannelInviteCodeUsageUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.SetBonusGrantedAt(v)
	})
}

// UpdateBonusGrantedAt sets the "bonus_granted_at" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsertOne) UpdateBonusGrantedAt() *ChannelInviteCodeUsageUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.UpdateBonusGrantedAt()
	})
}

// ClearBonusGrantedAt clears the value of the "bonus_granted_at" field.
func (u *ChannelInviteCodeUsageUpsertOne) ClearBonusGrantedAt() *ChannelInviteCodeUsageUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.ClearBonusGrantedAt()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *ChannelInviteCodeUsageUpsertOne) SetClaimedAt(v time.Time) *ChannelInviteCodeUsageUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsertOne) UpdateClaimedAt() *ChannelInviteCodeUsageUpsertOne {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.UpdateClaimedAt()
	})
}

// Exec executes the query.
func (u *ChannelInviteCodeUsageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelInviteCodeUsageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelInviteCodeUsageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelInviteCodeUsageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelInviteCodeUsageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelInviteCodeUsageCreateBulk is the builder for creating many ChannelInviteCodeUsage entities in bulk.
type ChannelInviteCodeUsageCreateBulk struct {
	config
	err      error
	builders []*ChannelInviteCodeUsageCreate
	conflict []sql.ConflictOption
}

// Save creates the ChannelInviteCodeUsage entities in the database.
func (_c *ChannelInviteCodeUsageCreateBulk) Save(ctx context.Context) ([]*ChannelInviteCodeUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelInviteCodeUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelInviteCodeUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelInviteCodeUsageCreateBulk) SaveX(ctx context.Context) []*ChannelInviteCodeUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelInviteCodeUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelInviteCodeUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelInviteCodeUsage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelInviteCodeUsageUpsert) {
//			SetCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelInviteCodeUsageCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelInviteCodeUsageUpsertBulk {
	_c.conflict = opts
	return &ChannelInviteCodeUsageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelInviteCodeUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelInviteCodeUsageCreateBulk) OnConflictColumns(columns ...string) *ChannelInviteCodeUsageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelInviteCodeUsageUpsertBulk{
		create: _c,
	}
}

// ChannelInviteCodeUsageUpsertBulk is the builder for "upsert"-ing
// a bulk of ChannelInviteCodeUsage nodes.
type ChannelInviteCodeUsageUpsertBulk struct {
	create *ChannelInviteCodeUsageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChannelInviteCodeUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelInviteCodeUsageUpsertBulk) UpdateNewValues() *ChannelInviteCodeUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelInviteCodeUsage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelInviteCodeUsageUpsertBulk) Ignore() *ChannelInviteCodeUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelInviteCodeUsageUpsertBulk) DoNothing() *ChannelInviteCodeUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelInviteCodeUsageCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelInviteCodeUsageUpsertBulk) Update(set func(*ChannelInviteCodeUsageUpsert)) *ChannelInviteCodeUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelInviteCodeUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetCodeID sets the "code_id" field.
func (u *ChannelInviteCodeUsageUpsertBulk) SetCodeID(v int64) *ChannelInviteCodeUsageUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.SetCodeID(v)
	})
}

// UpdateCodeID sets the "code_id" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsertBulk) UpdateCodeID() *ChannelInviteCodeUsageUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.UpdateCodeID()
	})
}

// SetBatchID sets the "batch_id" field.
func (u *ChannelInviteCodeUsageUpsertBulk) SetBatchID(v int64) *ChannelInviteCodeUsageUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.SetBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsertBulk) UpdateBatchID() *ChannelInviteCodeUsageUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.UpdateBatchID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ChannelInviteCodeUsageUpsertBulk) SetUserID(v int64) *ChannelInviteCodeUsageUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsertBulk) UpdateUserID() *ChannelInviteCodeUsageUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetBonusGranted sets the "bonus_granted" field.
func (u *ChannelInviteCodeUsageUpsertBulk) SetBonusGranted(v bool) *ChannelInviteCodeUsageUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.SetBonusGranted(v)
	})
}

// UpdateBonusGranted sets the "bonus_granted" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsertBulk) UpdateBonusGranted() *ChannelInviteCodeUsageUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.UpdateBonusGranted()
	})
}

// SetBonusGrantedAt sets the "bonus_granted_at" field.
func (u *ChannelInviteCodeUsageUpsertBulk) SetBonusGrantedAt(v time.Time) *ChannelInviteCodeUsageUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.SetBonusGrantedAt(v)
	})
}

// UpdateBonusGrantedAt sets the "bonus_granted_at" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsertBulk) UpdateBonusGrantedAt() *ChannelInviteCodeUsageUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.UpdateBonusGrantedAt()
	})
}

// ClearBonusGrantedAt clears the value of the "bonus_granted_at" field.
func (u *ChannelInviteCodeUsageUpsertBulk) ClearBonusGrantedAt() *ChannelInviteCodeUsageUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.ClearBonusGrantedAt()
	})
}

// SetClaimedAt sets the "claimed_at" field.
func (u *ChannelInviteCodeUsageUpsertBulk) SetClaimedAt(v time.Time) *ChannelInviteCodeUsageUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.SetClaimedAt(v)
	})
}

// UpdateClaimedAt sets the "claimed_at" field to the value that was provided on create.
func (u *ChannelInviteCodeUsageUpsertBulk) UpdateClaimedAt() *ChannelInviteCodeUsageUpsertBulk {
	return u.Update(func(s *ChannelInviteCodeUsageUpsert) {
		s.UpdateClaimedAt()
	})
}

// Exec executes the query.
func (u *ChannelInviteCodeUsageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelInviteCodeUsageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelInviteCodeUsageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelInviteCodeUsageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
