// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/groupvisibleplan"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupVisiblePlanDelete is the builder for deleting a GroupVisiblePlan entity.
type GroupVisiblePlanDelete struct {
	config
	hooks    []Hook
	mutation *GroupVisiblePlanMutation
}

// Where appends a list predicates to the GroupVisiblePlanDelete builder.
func (_d *GroupVisiblePlanDelete) Where(ps ...predicate.GroupVisiblePlan) *GroupVisiblePlanDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupVisiblePlanDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupVisiblePlanDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupVisiblePlanDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(groupvisibleplan.Table, nil)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupVisiblePlanDeleteOne is the builder for deleting a single GroupVisiblePlan entity.
type GroupVisiblePlanDeleteOne struct {
	_d *GroupVisiblePlanDelete
}

// Where appends a list predicates to the GroupVisiblePlanDelete builder.
func (_d *GroupVisiblePlanDeleteOne) Where(ps ...predicate.GroupVisiblePlan) *GroupVisiblePlanDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupVisiblePlanDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupvisibleplan.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupVisiblePlanDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
