// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupvisibleplan"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
)

// GroupVisiblePlanCreate is the builder for creating a GroupVisiblePlan entity.
type GroupVisiblePlanCreate struct {
	config
	mutation *GroupVisiblePlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGroupID sets the "group_id" field.
func (_c *GroupVisiblePlanCreate) SetGroupID(v int64) *GroupVisiblePlanCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *GroupVisiblePlanCreate) SetPlanID(v int64) *GroupVisiblePlanCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupVisiblePlanCreate) SetCreatedAt(v time.Time) *GroupVisiblePlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupVisiblePlanCreate) SetNillableCreatedAt(v *time.Time) *GroupVisiblePlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupVisiblePlanCreate) SetGroup(v *Group) *GroupVisiblePlanCreate {
	return _c.SetGroupID(v.ID)
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_c *GroupVisiblePlanCreate) SetPlan(v *SubscriptionPlan) *GroupVisiblePlanCreate {
	return _c.SetPlanID(v.ID)
}

// Mutation returns the GroupVisiblePlanMutation object of the builder.
func (_c *GroupVisiblePlanCreate) Mutation() *GroupVisiblePlanMutation {
	return _c.mutation
}

// Save creates the GroupVisiblePlan in the database.
func (_c *GroupVisiblePlanCreate) Save(ctx context.Context) (*GroupVisiblePlan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupVisiblePlanCreate) SaveX(ctx context.Context) *GroupVisiblePlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupVisiblePlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupVisiblePlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupVisiblePlanCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := groupvisibleplan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupVisiblePlanCreate) check() error {
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupVisiblePlan.group_id"`)}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "GroupVisiblePlan.plan_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupVisiblePlan.created_at"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupVisiblePlan.group"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "GroupVisiblePlan.plan"`)}
	}
	return nil
}

func (_c *GroupVisiblePlanCreate) sqlSave(ctx context.Context) (*GroupVisiblePlan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *GroupVisiblePlanCreate) createSpec() (*GroupVisiblePlan, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupVisiblePlan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupvisibleplan.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupvisibleplan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupvisibleplan.GroupTable,
			Columns: []string{groupvisibleplan.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupvisibleplan.PlanTable,
			Columns: []string{groupvisibleplan.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupVisiblePlan.Create().
//		SetGroupID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupVisiblePlanUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupVisiblePlanCreate) OnConflict(opts ...sql.ConflictOption) *GroupVisiblePlanUpsertOne {
	_c.conflict = opts
	return &GroupVisiblePlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupVisiblePlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupVisiblePlanCreate) OnConflictColumns(columns ...string) *GroupVisiblePlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupVisiblePlanUpsertOne{
		create: _c,
	}
}

type (
	// GroupVisiblePlanUpsertOne is the builder for "upsert"-ing
	//  one GroupVisiblePlan node.
	GroupVisiblePlanUpsertOne struct {
		create *GroupVisiblePlanCreate
	}

	// GroupVisiblePlanUpsert is the "OnConflict" setter.
	GroupVisiblePlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetGroupID sets the "group_id" field.
func (u *GroupVisiblePlanUpsert) SetGroupID(v int64) *GroupVisiblePlanUpsert {
	u.Set(groupvisibleplan.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupVisiblePlanUpsert) UpdateGroupID() *GroupVisiblePlanUpsert {
	u.SetExcluded(groupvisibleplan.FieldGroupID)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *GroupVisiblePlanUpsert) SetPlanID(v int64) *GroupVisiblePlanUpsert {
	u.Set(groupvisibleplan.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *GroupVisiblePlanUpsert) UpdatePlanID() *GroupVisiblePlanUpsert {
	u.SetExcluded(groupvisibleplan.FieldPlanID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupVisiblePlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupVisiblePlanUpsertOne) UpdateNewValues() *GroupVisiblePlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(groupvisibleplan.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupVisiblePlan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupVisiblePlanUpsertOne) Ignore() *GroupVisiblePlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupVisiblePlanUpsertOne) DoNothing() *GroupVisiblePlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupVisiblePlanCreate.OnConflict
// documentation for more info.
func (u *GroupVisiblePlanUpsertOne) Update(set func(*GroupVisiblePlanUpsert)) *GroupVisiblePlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupVisiblePlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupVisiblePlanUpsertOne) SetGroupID(v int64) *GroupVisiblePlanUpsertOne {
	return u.Update(func(s *GroupVisiblePlanUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupVisiblePlanUpsertOne) UpdateGroupID() *GroupVisiblePlanUpsertOne {
	return u.Update(func(s *GroupVisiblePlanUpsert) {
		s.UpdateGroupID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *GroupVisiblePlanUpsertOne) SetPlanID(v int64) *GroupVisiblePlanUpsertOne {
	return u.Update(func(s *GroupVisiblePlanUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *GroupVisiblePlanUpsertOne) UpdatePlanID() *GroupVisiblePlanUpsertOne {
	return u.Update(func(s *GroupVisiblePlanUpsert) {
		s.UpdatePlanID()
	})
}

// Exec executes the query.
func (u *GroupVisiblePlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupVisiblePlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupVisiblePlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// GroupVisiblePlanCreateBulk is the builder for creating many GroupVisiblePlan entities in bulk.
type GroupVisiblePlanCreateBulk struct {
	config
	err      error
	builders []*GroupVisiblePlanCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupVisiblePlan entities in the database.
func (_c *GroupVisiblePlanCreateBulk) Save(ctx context.Context) ([]*GroupVisiblePlan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupVisiblePlan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupVisiblePlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupVisiblePlanCreateBulk) SaveX(ctx context.Context) []*GroupVisiblePlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupVisiblePlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupVisiblePlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupVisiblePlan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupVisiblePlanUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupVisiblePlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupVisiblePlanUpsertBulk {
	_c.conflict = opts
	return &GroupVisiblePlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupVisiblePlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupVisiblePlanCreateBulk) OnConflictColumns(columns ...string) *GroupVisiblePlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupVisiblePlanUpsertBulk{
		create: _c,
	}
}

// GroupVisiblePlanUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupVisiblePlan nodes.
type GroupVisiblePlanUpsertBulk struct {
	create *GroupVisiblePlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupVisiblePlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupVisiblePlanUpsertBulk) UpdateNewValues() *GroupVisiblePlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(groupvisibleplan.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupVisiblePlan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupVisiblePlanUpsertBulk) Ignore() *GroupVisiblePlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupVisiblePlanUpsertBulk) DoNothing() *GroupVisiblePlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupVisiblePlanCreateBulk.OnConflict
// documentation for more info.
func (u *GroupVisiblePlanUpsertBulk) Update(set func(*GroupVisiblePlanUpsert)) *GroupVisiblePlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupVisiblePlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupVisiblePlanUpsertBulk) SetGroupID(v int64) *GroupVisiblePlanUpsertBulk {
	return u.Update(func(s *GroupVisiblePlanUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupVisiblePlanUpsertBulk) UpdateGroupID() *GroupVisiblePlanUpsertBulk {
	return u.Update(func(s *GroupVisiblePlanUpsert) {
		s.UpdateGroupID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *GroupVisiblePlanUpsertBulk) SetPlanID(v int64) *GroupVisiblePlanUpsertBulk {
	return u.Update(func(s *GroupVisiblePlanUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *GroupVisiblePlanUpsertBulk) UpdatePlanID() *GroupVisiblePlanUpsertBulk {
	return u.Update(func(s *GroupVisiblePlanUpsert) {
		s.UpdatePlanID()
	})
}

// Exec executes the query.
func (u *GroupVisiblePlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupVisiblePlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupVisiblePlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupVisiblePlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
