// Code generated by ent, DO NOT EDIT.

package channelinvitecodeusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the channelinvitecodeusage type in the database.
	Label = "channel_invite_code_usage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCodeID holds the string denoting the code_id field in the database.
	FieldCodeID = "code_id"
	// FieldBatchID holds the string denoting the batch_id field in the database.
	FieldBatchID = "batch_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldBonusGranted holds the string denoting the bonus_granted field in the database.
	FieldBonusGranted = "bonus_granted"
	// FieldBonusGrantedAt holds the string denoting the bonus_granted_at field in the database.
	FieldBonusGrantedAt = "bonus_granted_at"
	// FieldClaimedAt holds the string denoting the claimed_at field in the database.
	FieldClaimedAt = "claimed_at"
	// EdgeCode holds the string denoting the code edge name in mutations.
	EdgeCode = "code"
	// EdgeBatch holds the string denoting the batch edge name in mutations.
	EdgeBatch = "batch"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the channelinvitecodeusage in the database.
	Table = "channel_invite_code_usages"
	// CodeTable is the table that holds the code relation/edge.
	CodeTable = "channel_invite_code_usages"
	// CodeInverseTable is the table name for the ChannelInviteCode entity.
	// It exists in this package in order to avoid circular dependency with the "channelinvitecode" package.
	CodeInverseTable = "channel_invite_codes"
	// CodeColumn is the table column denoting the code relation/edge.
	CodeColumn = "code_id"
	// BatchTable is the table that holds the batch relation/edge.
	BatchTable = "channel_invite_code_usages"
	// BatchInverseTable is the table name for the ChannelInviteBatch entity.
	// It exists in this package in order to avoid circular dependency with the "channelinvitebatch" package.
	BatchInverseTable = "channel_invite_batches"
	// BatchColumn is the table column denoting the batch relation/edge.
	BatchColumn = "batch_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "channel_invite_code_usages"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for channelinvitecodeusage fields.
var Columns = []string{
	FieldID,
	FieldCodeID,
	FieldBatchID,
	FieldUserID,
	FieldBonusGranted,
	FieldBonusGrantedAt,
	FieldClaimedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBonusGranted holds the default value on creation for the "bonus_granted" field.
	DefaultBonusGranted bool
	// DefaultClaimedAt holds the default value on creation for the "claimed_at" field.
	DefaultClaimedAt func() time.Time
)

// OrderOption defines the ordering options for the ChannelInviteCodeUsage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCodeID orders the results by the code_id field.
func ByCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodeID, opts...).ToFunc()
}

// ByBatchID orders the results by the batch_id field.
func ByBatchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByBonusGranted orders the results by the bonus_granted field.
func ByBonusGranted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBonusGranted, opts...).ToFunc()
}

// ByBonusGrantedAt orders the results by the bonus_granted_at field.
func ByBonusGrantedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBonusGrantedAt, opts...).ToFunc()
}

// ByClaimedAt orders the results by the claimed_at field.
func ByClaimedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimedAt, opts...).ToFunc()
}

// ByCodeField orders the results by code field.
func ByCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByBatchField orders the results by batch field.
func ByBatchField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBatchStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CodeTable, CodeColumn),
	)
}
func newBatchStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BatchInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BatchTable, BatchColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
