// Code generated by ent, DO NOT EDIT.

package channelinvitecodeusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldLTE(FieldID, id))
}

// CodeID applies equality check predicate on the "code_id" field. It's identical to CodeIDEQ.
func CodeID(v int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldCodeID, v))
}

// BatchID applies equality check predicate on the "batch_id" field. It's identical to BatchIDEQ.
func BatchID(v int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldBatchID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldUserID, v))
}

// BonusGranted applies equality check predicate on the "bonus_granted" field. It's identical to BonusGrantedEQ.
func BonusGranted(v bool) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldBonusGranted, v))
}

// BonusGrantedAt applies equality check predicate on the "bonus_granted_at" field. It's identical to BonusGrantedAtEQ.
func BonusGrantedAt(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldBonusGrantedAt, v))
}

// ClaimedAt applies equality check predicate on the "claimed_at" field. It's identical to ClaimedAtEQ.
func ClaimedAt(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldClaimedAt, v))
}

// CodeIDEQ applies the EQ predicate on the "code_id" field.
func CodeIDEQ(v int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldCodeID, v))
}

// CodeIDNEQ applies the NEQ predicate on the "code_id" field.
func CodeIDNEQ(v int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNEQ(FieldCodeID, v))
}

// CodeIDIn applies the In predicate on the "code_id" field.
func CodeIDIn(vs ...int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldIn(FieldCodeID, vs...))
}

// CodeIDNotIn applies the NotIn predicate on the "code_id" field.
func CodeIDNotIn(vs ...int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNotIn(FieldCodeID, vs...))
}

// BatchIDEQ applies the EQ predicate on the "batch_id" field.
func BatchIDEQ(v int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldBatchID, v))
}

// BatchIDNEQ applies the NEQ predicate on the "batch_id" field.
func BatchIDNEQ(v int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNEQ(FieldBatchID, v))
}

// BatchIDIn applies the In predicate on the "batch_id" field.
func BatchIDIn(vs ...int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldIn(FieldBatchID, vs...))
}

// BatchIDNotIn applies the NotIn predicate on the "batch_id" field.
func BatchIDNotIn(vs ...int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNotIn(FieldBatchID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNotIn(FieldUserID, vs...))
}

// BonusGrantedEQ applies the EQ predicate on the "bonus_granted" field.
func BonusGrantedEQ(v bool) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldBonusGranted, v))
}

// BonusGrantedNEQ applies the NEQ predicate on the "bonus_granted" field.
func BonusGrantedNEQ(v bool) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNEQ(FieldBonusGranted, v))
}

// BonusGrantedAtEQ applies the EQ predicate on the "bonus_granted_at" field.
func BonusGrantedAtEQ(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldBonusGrantedAt, v))
}

// BonusGrantedAtNEQ applies the NEQ predicate on the "bonus_granted_at" field.
func BonusGrantedAtNEQ(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNEQ(FieldBonusGrantedAt, v))
}

// BonusGrantedAtIn applies the In predicate on the "bonus_granted_at" field.
func BonusGrantedAtIn(vs ...time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldIn(FieldBonusGrantedAt, vs...))
}

// BonusGrantedAtNotIn applies the NotIn predicate on the "bonus_granted_at" field.
func BonusGrantedAtNotIn(vs ...time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNotIn(FieldBonusGrantedAt, vs...))
}

// BonusGrantedAtGT applies the GT predicate on the "bonus_granted_at" field.
func BonusGrantedAtGT(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldGT(FieldBonusGrantedAt, v))
}

// BonusGrantedAtGTE applies the GTE predicate on the "bonus_granted_at" field.
func BonusGrantedAtGTE(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldGTE(FieldBonusGrantedAt, v))
}

// BonusGrantedAtLT applies the LT predicate on the "bonus_granted_at" field.
func BonusGrantedAtLT(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldLT(FieldBonusGrantedAt, v))
}

// BonusGrantedAtLTE applies the LTE predicate on the "bonus_granted_at" field.
func BonusGrantedAtLTE(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldLTE(FieldBonusGrantedAt, v))
}

// BonusGrantedAtIsNil applies the IsNil predicate on the "bonus_granted_at" field.
func BonusGrantedAtIsNil() predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldIsNull(FieldBonusGrantedAt))
}

// BonusGrantedAtNotNil applies the NotNil predicate on the "bonus_granted_at" field.
func BonusGrantedAtNotNil() predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNotNull(FieldBonusGrantedAt))
}

// ClaimedAtEQ applies the EQ predicate on the "claimed_at" field.
func ClaimedAtEQ(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldEQ(FieldClaimedAt, v))
}

// ClaimedAtNEQ applies the NEQ predicate on the "claimed_at" field.
func ClaimedAtNEQ(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNEQ(FieldClaimedAt, v))
}

// ClaimedAtIn applies the In predicate on the "claimed_at" field.
func ClaimedAtIn(vs ...time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldIn(FieldClaimedAt, vs...))
}

// ClaimedAtNotIn applies the NotIn predicate on the "claimed_at" field.
func ClaimedAtNotIn(vs ...time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldNotIn(FieldClaimedAt, vs...))
}

// ClaimedAtGT applies the GT predicate on the "claimed_at" field.
func ClaimedAtGT(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldGT(FieldClaimedAt, v))
}

// ClaimedAtGTE applies the GTE predicate on the "claimed_at" field.
func ClaimedAtGTE(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldGTE(FieldClaimedAt, v))
}

// ClaimedAtLT applies the LT predicate on the "claimed_at" field.
func ClaimedAtLT(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldLT(FieldClaimedAt, v))
}

// ClaimedAtLTE applies the LTE predicate on the "claimed_at" field.
func ClaimedAtLTE(v time.Time) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.FieldLTE(FieldClaimedAt, v))
}

// HasCode applies the HasEdge predicate on the "code" edge.
func HasCode() predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CodeTable, CodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCodeWith applies the HasEdge predicate on the "code" edge with a given conditions (other predicates).
func HasCodeWith(preds ...predicate.ChannelInviteCode) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(func(s *sql.Selector) {
		step := newCodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBatch applies the HasEdge predicate on the "batch" edge.
func HasBatch() predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BatchTable, BatchColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBatchWith applies the HasEdge predicate on the "batch" edge with a given conditions (other predicates).
func HasBatchWith(preds ...predicate.ChannelInviteBatch) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(func(s *sql.Selector) {
		step := newBatchStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChannelInviteCodeUsage) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChannelInviteCodeUsage) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChannelInviteCodeUsage) predicate.ChannelInviteCodeUsage {
	return predicate.ChannelInviteCodeUsage(sql.NotPredicates(p))
}
