// Code generated by ent, DO NOT EDIT.

package channelinvitebatchgroup

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldLTE(FieldID, id))
}

// BatchID applies equality check predicate on the "batch_id" field. It's identical to BatchIDEQ.
func BatchID(v int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldEQ(FieldBatchID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldEQ(FieldGroupID, v))
}

// BatchIDEQ applies the EQ predicate on the "batch_id" field.
func BatchIDEQ(v int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldEQ(FieldBatchID, v))
}

// BatchIDNEQ applies the NEQ predicate on the "batch_id" field.
func BatchIDNEQ(v int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldNEQ(FieldBatchID, v))
}

// BatchIDIn applies the In predicate on the "batch_id" field.
func BatchIDIn(vs ...int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldIn(FieldBatchID, vs...))
}

// BatchIDNotIn applies the NotIn predicate on the "batch_id" field.
func BatchIDNotIn(vs ...int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldNotIn(FieldBatchID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.FieldNotIn(FieldGroupID, vs...))
}

// HasBatch applies the HasEdge predicate on the "batch" edge.
func HasBatch() predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BatchTable, BatchColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBatchWith applies the HasEdge predicate on the "batch" edge with a given conditions (other predicates).
func HasBatchWith(preds ...predicate.ChannelInviteBatch) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(func(s *sql.Selector) {
		step := newBatchStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChannelInviteBatchGroup) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChannelInviteBatchGroup) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChannelInviteBatchGroup) predicate.ChannelInviteBatchGroup {
	return predicate.ChannelInviteBatchGroup(sql.NotPredicates(p))
}
