// Code generated by ent, DO NOT EDIT.

package channelinvitebatch

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the channelinvitebatch type in the database.
	Label = "channel_invite_batch"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldBonusAmount holds the string denoting the bonus_amount field in the database.
	FieldBonusAmount = "bonus_amount"
	// FieldMaxUsesPerCode holds the string denoting the max_uses_per_code field in the database.
	FieldMaxUsesPerCode = "max_uses_per_code"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldActivityCopyText holds the string denoting the activity_copy_text field in the database.
	FieldActivityCopyText = "activity_copy_text"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// EdgeCodes holds the string denoting the codes edge name in mutations.
	EdgeCodes = "codes"
	// EdgeBatchGroups holds the string denoting the batch_groups edge name in mutations.
	EdgeBatchGroups = "batch_groups"
	// EdgeUsages holds the string denoting the usages edge name in mutations.
	EdgeUsages = "usages"
	// Table holds the table name of the channelinvitebatch in the database.
	Table = "channel_invite_batches"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "channel_invite_batches"
	// CreatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatorInverseTable = "users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "created_by"
	// CodesTable is the table that holds the codes relation/edge.
	CodesTable = "channel_invite_codes"
	// CodesInverseTable is the table name for the ChannelInviteCode entity.
	// It exists in this package in order to avoid circular dependency with the "channelinvitecode" package.
	CodesInverseTable = "channel_invite_codes"
	// CodesColumn is the table column denoting the codes relation/edge.
	CodesColumn = "batch_id"
	// BatchGroupsTable is the table that holds the batch_groups relation/edge.
	BatchGroupsTable = "channel_invite_batch_groups"
	// BatchGroupsInverseTable is the table name for the ChannelInviteBatchGroup entity.
	// It exists in this package in order to avoid circular dependency with the "channelinvitebatchgroup" package.
	BatchGroupsInverseTable = "channel_invite_batch_groups"
	// BatchGroupsColumn is the table column denoting the batch_groups relation/edge.
	BatchGroupsColumn = "batch_id"
	// UsagesTable is the table that holds the usages relation/edge.
	UsagesTable = "channel_invite_code_usages"
	// UsagesInverseTable is the table name for the ChannelInviteCodeUsage entity.
	// It exists in this package in order to avoid circular dependency with the "channelinvitecodeusage" package.
	UsagesInverseTable = "channel_invite_code_usages"
	// UsagesColumn is the table column denoting the usages relation/edge.
	UsagesColumn = "batch_id"
)

// Columns holds all SQL columns for channelinvitebatch fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldBonusAmount,
	FieldMaxUsesPerCode,
	FieldStartTime,
	FieldEndTime,
	FieldStatus,
	FieldNotes,
	FieldActivityCopyText,
	FieldCreatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultBonusAmount holds the default value on creation for the "bonus_amount" field.
	DefaultBonusAmount float64
	// DefaultMaxUsesPerCode holds the default value on creation for the "max_uses_per_code" field.
	DefaultMaxUsesPerCode int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ChannelInviteBatch queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByBonusAmount orders the results by the bonus_amount field.
func ByBonusAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBonusAmount, opts...).ToFunc()
}

// ByMaxUsesPerCode orders the results by the max_uses_per_code field.
func ByMaxUsesPerCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxUsesPerCode, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByEndTime orders the results by the end_time field.
func ByEndTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndTime, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByActivityCopyText orders the results by the activity_copy_text field.
func ByActivityCopyText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivityCopyText, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}

// ByCodesCount orders the results by codes count.
func ByCodesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCodesStep(), opts...)
	}
}

// ByCodes orders the results by codes terms.
func ByCodes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCodesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBatchGroupsCount orders the results by batch_groups count.
func ByBatchGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBatchGroupsStep(), opts...)
	}
}

// ByBatchGroups orders the results by batch_groups terms.
func ByBatchGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBatchGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUsagesCount orders the results by usages count.
func ByUsagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsagesStep(), opts...)
	}
}

// ByUsages orders the results by usages terms.
func ByUsages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
	)
}
func newCodesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CodesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CodesTable, CodesColumn),
	)
}
func newBatchGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BatchGroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BatchGroupsTable, BatchGroupsColumn),
	)
}
func newUsagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsagesTable, UsagesColumn),
	)
}
