// Code generated by ent, DO NOT EDIT.

package channelinvitebatch

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldName, v))
}

// BonusAmount applies equality check predicate on the "bonus_amount" field. It's identical to BonusAmountEQ.
func BonusAmount(v float64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldBonusAmount, v))
}

// MaxUsesPerCode applies equality check predicate on the "max_uses_per_code" field. It's identical to MaxUsesPerCodeEQ.
func MaxUsesPerCode(v int) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldMaxUsesPerCode, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldStartTime, v))
}

// EndTime applies equality check predicate on the "end_time" field. It's identical to EndTimeEQ.
func EndTime(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldEndTime, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldStatus, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldNotes, v))
}

// ActivityCopyText applies equality check predicate on the "activity_copy_text" field. It's identical to ActivityCopyTextEQ.
func ActivityCopyText(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldActivityCopyText, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldContainsFold(FieldName, v))
}

// BonusAmountEQ applies the EQ predicate on the "bonus_amount" field.
func BonusAmountEQ(v float64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldBonusAmount, v))
}

// BonusAmountNEQ applies the NEQ predicate on the "bonus_amount" field.
func BonusAmountNEQ(v float64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNEQ(FieldBonusAmount, v))
}

// BonusAmountIn applies the In predicate on the "bonus_amount" field.
func BonusAmountIn(vs ...float64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIn(FieldBonusAmount, vs...))
}

// BonusAmountNotIn applies the NotIn predicate on the "bonus_amount" field.
func BonusAmountNotIn(vs ...float64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotIn(FieldBonusAmount, vs...))
}

// BonusAmountGT applies the GT predicate on the "bonus_amount" field.
func BonusAmountGT(v float64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGT(FieldBonusAmount, v))
}

// BonusAmountGTE applies the GTE predicate on the "bonus_amount" field.
func BonusAmountGTE(v float64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGTE(FieldBonusAmount, v))
}

// BonusAmountLT applies the LT predicate on the "bonus_amount" field.
func BonusAmountLT(v float64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLT(FieldBonusAmount, v))
}

// BonusAmountLTE applies the LTE predicate on the "bonus_amount" field.
func BonusAmountLTE(v float64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLTE(FieldBonusAmount, v))
}

// MaxUsesPerCodeEQ applies the EQ predicate on the "max_uses_per_code" field.
func MaxUsesPerCodeEQ(v int) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldMaxUsesPerCode, v))
}

// MaxUsesPerCodeNEQ applies the NEQ predicate on the "max_uses_per_code" field.
func MaxUsesPerCodeNEQ(v int) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNEQ(FieldMaxUsesPerCode, v))
}

// MaxUsesPerCodeIn applies the In predicate on the "max_uses_per_code" field.
func MaxUsesPerCodeIn(vs ...int) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIn(FieldMaxUsesPerCode, vs...))
}

// MaxUsesPerCodeNotIn applies the NotIn predicate on the "max_uses_per_code" field.
func MaxUsesPerCodeNotIn(vs ...int) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotIn(FieldMaxUsesPerCode, vs...))
}

// MaxUsesPerCodeGT applies the GT predicate on the "max_uses_per_code" field.
func MaxUsesPerCodeGT(v int) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGT(FieldMaxUsesPerCode, v))
}

// MaxUsesPerCodeGTE applies the GTE predicate on the "max_uses_per_code" field.
func MaxUsesPerCodeGTE(v int) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGTE(FieldMaxUsesPerCode, v))
}

// MaxUsesPerCodeLT applies the LT predicate on the "max_uses_per_code" field.
func MaxUsesPerCodeLT(v int) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLT(FieldMaxUsesPerCode, v))
}

// MaxUsesPerCodeLTE applies the LTE predicate on the "max_uses_per_code" field.
func MaxUsesPerCodeLTE(v int) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLTE(FieldMaxUsesPerCode, v))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLTE(FieldStartTime, v))
}

// StartTimeIsNil applies the IsNil predicate on the "start_time" field.
func StartTimeIsNil() predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIsNull(FieldStartTime))
}

// StartTimeNotNil applies the NotNil predicate on the "start_time" field.
func StartTimeNotNil() predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotNull(FieldStartTime))
}

// EndTimeEQ applies the EQ predicate on the "end_time" field.
func EndTimeEQ(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldEndTime, v))
}

// EndTimeNEQ applies the NEQ predicate on the "end_time" field.
func EndTimeNEQ(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNEQ(FieldEndTime, v))
}

// EndTimeIn applies the In predicate on the "end_time" field.
func EndTimeIn(vs ...time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIn(FieldEndTime, vs...))
}

// EndTimeNotIn applies the NotIn predicate on the "end_time" field.
func EndTimeNotIn(vs ...time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotIn(FieldEndTime, vs...))
}

// EndTimeGT applies the GT predicate on the "end_time" field.
func EndTimeGT(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGT(FieldEndTime, v))
}

// EndTimeGTE applies the GTE predicate on the "end_time" field.
func EndTimeGTE(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGTE(FieldEndTime, v))
}

// EndTimeLT applies the LT predicate on the "end_time" field.
func EndTimeLT(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLT(FieldEndTime, v))
}

// EndTimeLTE applies the LTE predicate on the "end_time" field.
func EndTimeLTE(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLTE(FieldEndTime, v))
}

// EndTimeIsNil applies the IsNil predicate on the "end_time" field.
func EndTimeIsNil() predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIsNull(FieldEndTime))
}

// EndTimeNotNil applies the NotNil predicate on the "end_time" field.
func EndTimeNotNil() predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotNull(FieldEndTime))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldContainsFold(FieldStatus, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldContainsFold(FieldNotes, v))
}

// ActivityCopyTextEQ applies the EQ predicate on the "activity_copy_text" field.
func ActivityCopyTextEQ(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldActivityCopyText, v))
}

// ActivityCopyTextNEQ applies the NEQ predicate on the "activity_copy_text" field.
func ActivityCopyTextNEQ(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNEQ(FieldActivityCopyText, v))
}

// ActivityCopyTextIn applies the In predicate on the "activity_copy_text" field.
func ActivityCopyTextIn(vs ...string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIn(FieldActivityCopyText, vs...))
}

// ActivityCopyTextNotIn applies the NotIn predicate on the "activity_copy_text" field.
func ActivityCopyTextNotIn(vs ...string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotIn(FieldActivityCopyText, vs...))
}

// ActivityCopyTextGT applies the GT predicate on the "activity_copy_text" field.
func ActivityCopyTextGT(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGT(FieldActivityCopyText, v))
}

// ActivityCopyTextGTE applies the GTE predicate on the "activity_copy_text" field.
func ActivityCopyTextGTE(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGTE(FieldActivityCopyText, v))
}

// ActivityCopyTextLT applies the LT predicate on the "activity_copy_text" field.
func ActivityCopyTextLT(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLT(FieldActivityCopyText, v))
}

// ActivityCopyTextLTE applies the LTE predicate on the "activity_copy_text" field.
func ActivityCopyTextLTE(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLTE(FieldActivityCopyText, v))
}

// ActivityCopyTextContains applies the Contains predicate on the "activity_copy_text" field.
func ActivityCopyTextContains(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldContains(FieldActivityCopyText, v))
}

// ActivityCopyTextHasPrefix applies the HasPrefix predicate on the "activity_copy_text" field.
func ActivityCopyTextHasPrefix(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldHasPrefix(FieldActivityCopyText, v))
}

// ActivityCopyTextHasSuffix applies the HasSuffix predicate on the "activity_copy_text" field.
func ActivityCopyTextHasSuffix(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldHasSuffix(FieldActivityCopyText, v))
}

// ActivityCopyTextIsNil applies the IsNil predicate on the "activity_copy_text" field.
func ActivityCopyTextIsNil() predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIsNull(FieldActivityCopyText))
}

// ActivityCopyTextNotNil applies the NotNil predicate on the "activity_copy_text" field.
func ActivityCopyTextNotNil() predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotNull(FieldActivityCopyText))
}

// ActivityCopyTextEqualFold applies the EqualFold predicate on the "activity_copy_text" field.
func ActivityCopyTextEqualFold(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEqualFold(FieldActivityCopyText, v))
}

// ActivityCopyTextContainsFold applies the ContainsFold predicate on the "activity_copy_text" field.
func ActivityCopyTextContainsFold(v string) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldContainsFold(FieldActivityCopyText, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCodes applies the HasEdge predicate on the "codes" edge.
func HasCodes() predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CodesTable, CodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCodesWith applies the HasEdge predicate on the "codes" edge with a given conditions (other predicates).
func HasCodesWith(preds ...predicate.ChannelInviteCode) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(func(s *sql.Selector) {
		step := newCodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBatchGroups applies the HasEdge predicate on the "batch_groups" edge.
func HasBatchGroups() predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BatchGroupsTable, BatchGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBatchGroupsWith applies the HasEdge predicate on the "batch_groups" edge with a given conditions (other predicates).
func HasBatchGroupsWith(preds ...predicate.ChannelInviteBatchGroup) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(func(s *sql.Selector) {
		step := newBatchGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsages applies the HasEdge predicate on the "usages" edge.
func HasUsages() predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsagesTable, UsagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsagesWith applies the HasEdge predicate on the "usages" edge with a given conditions (other predicates).
func HasUsagesWith(preds ...predicate.ChannelInviteCodeUsage) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(func(s *sql.Selector) {
		step := newUsagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChannelInviteBatch) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChannelInviteBatch) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChannelInviteBatch) predicate.ChannelInviteBatch {
	return predicate.ChannelInviteBatch(sql.NotPredicates(p))
}
